### ISSUE TITLE
Error Getting List of Followers

### ISSUE THREAD

**Issue by AlexeyKosov** [seregazhuk/php-pinterest-bot#10]
`$pinterest->pinners->followers($username)` produces an error:

    'resource_response' =>
    array(2) {
      'data' =>
      NULL
      'error' =>
      array(5) {
        'api_error_code' =>
        int(30)
        'message' =>
        string(15) "User not found."
        'code' =>
        string(9) "API_ERROR"
        'target' =>
        string(66) "<webapp.resources.user_resource.UserResource object at 0x1b26f110>"
        'http_status' =>
        int(404)
      }
    }

The error throws for any valid `$username`.

**Comment by AlexeyKosov** [comment]
The error can be fixed by changing 

    protected static function createPinnerRequestData($username)
    {
        return [
            "options" => [
                "username_or_email" => $username,
            ],
            "context" => new \stdClass(),
        ];
    }

to 

    protected static function createPinnerRequestData($username)
    {
        return [
            "options" => [
                "username" => $username,
            ],
            "context" => new \stdClass(),
        ];
    }

in PinnerHelper.php

**Comment by seregazhuk** [comment]
@AlexeyKosov  thank you for issue, fixed.

**Comment by yashasvi12** [comment]
@AlexeyKosov and @seregazhuk Can i get the followers of the non authenticated user with this?

**Comment by seregazhuk** [comment]
@yashasvi12 If you don't want to log in, just provide empty strings to constructor:
```php
require 'vendor/autoload.php';

use seregazhuk\PinterestBot\PinterestBot;

$bot = new PinterestBot('', '');

foreach($bot->pinners->followers('username') as $followers)
{
    print_r($followers);
}

**Comment by yashasvi12** [comment]
the api which will be created will be like this rite?
https://api.pinterest.com/v1/username/followers/?access_token=ACCESS_TOKEN

**Comment by seregazhuk** [comment]
No, it works like your browser requests and does not require token.

**Comment by yashasvi12** [comment]
i was actually using https://github.com/dirkgroenen/Pinterest-API-PHP
any idea how i can get the users followers with this???

**Comment by seregazhuk** [comment]
No idea, ask the author of package.

**Comment by yashasvi12** [comment]
thanks
