### ISSUE TITLE
Like function not working

### ISSUE THREAD

**Issue by jellomaster** [seregazhuk/php-pinterest-bot#108]
I think the like function is broken.  I'm able to login, post a pin or get pin info.  However like doesn't seem to work, as the like count doesn't update on pinterest and the like function below doesn't return anything.  For example in the snip below, I'm able to login and $pin_info is an array with all the pin's info however $like_info doesn't return anything and the like count doesn't go up.

                $bot->login($usr, $pwd);
                $pin_info = $bot->pins->info($pin_id);
                print_r($pin_info);
                $like_info = $bot->pins->like($pin_id);
                print_r($like_info);

**Comment by seregazhuk** [comment]
Hi, @jellomaster, you are right, it doesn't work. Fixed in 3.2.3 version. Download the latest version of the library.
