### ISSUE TITLE
Pagination doesn't work

### ISSUE THREAD

**Issue by AlexeyKosov** [seregazhuk/php-pinterest-bot#12]
There's a bug in the function:

    RequestHelper.php:

    public static function createRequestData($data, $sourceUrl = null)
    {
        return [
            "source_url" => $sourceUrl,
            "data"       => json_encode($data, JSON_FORCE_OBJECT),
        ];
    }

Because of `JSON_FORCE_OBJECT`, bookmarks are encoded incorrectly:
     `{"0": "Pz9Nakl5TX...YxNmRjNQ=="}`
instead of 
     `["Pz9Nakl5TX...YxNmRjNQ=="]`

It makes the option invalid and the first page is always being returned.

**Comment by seregazhuk** [comment]
Wrong request in:
```
SearchHelper.php

protected static function createSimpleSearchRequest($requestData)
    {
        $dataJson = [
            'module' => [
                "name"    => "SearchPage",
                "options" => $requestData['options'],
            ],
            "options" => $requestData['options'],  // <-- was missed
        ];
        return $dataJson;
    }
```
I missed one more *options* param. 
Strange, but for pinns search it works fine.

**Comment by AlexeyKosov** [comment]
In my case it didn't work for iterating followers.

**Comment by seregazhuk** [comment]
I see, it didn't work for boards and pinners, only for pins. I'll fix it now.

**Comment by seregazhuk** [comment]
Try it now.

**Comment by AlexeyKosov** [comment]
Thanks!

**Comment by AlexeyKosov** [comment]
Looks like it didn't help, bookmarks are still being encoded to JSON object rather than array.

**Comment by seregazhuk** [comment]
Oh, I see. Sorry, I'll fix it soon.

**Comment by seregazhuk** [comment]
I think I have fixed it now)
