### ISSUE TITLE
Getting my own feed

### ISSUE THREAD

**Issue by misterkek** [seregazhuk/php-pinterest-bot#139]
How can I get my own feed that showing on the main page https://pinterest.com/?

**Comment by seregazhuk** [comment]
Hi @misterkek ! Yes, I've added it in the latest version (4.5.1).  Method *userFeed()* returns Iterator object.

```php
foreach ($bot->pins->userFeed() as $pin) {
    //...
}

// only first 20 pins from feed
foreach ($bot->pins->userFeed(20) as $pin) {
    //...
}
```
