### ISSUE TITLE
register method return false

### ISSUE THREAD

**Issue by snapmaster** [seregazhuk/php-pinterest-bot#167]
Hi,  great api :)

I am trying to create new profile with `register` mehtod and I've `false` any time I try..
Does it actually works?

thank you

**Comment by seregazhuk** [comment]
Hi @snapmaster !
I've checked it, and it works. Maybe validation fails, when you are trying to register. What is the output of this, after `register()` returns `false`:

```php
print_r($bot->getLastError());
```

**Comment by snapmaster** [comment]
Here is my output for print_r($bot->getLastError()):

`falseArray
(
    [code] => UNHANDLED_EXCEPTION_IN_RESOURCE
    [target] => <webapp.resources.user_register_resource.UserRegisterResource object at 0x1dabdf10>
    [http_status] => 500
)
`

**Comment by seregazhuk** [comment]
I can't figure out this error. What is your actual code? I'll try to reproduce this error myself.

**Comment by snapmaster** [comment]
Hm, it works if I do not specify age and region:

`<?php

require('vendor/autoload.php'); 

use seregazhuk\PinterestBot\Factories\PinterestBot;

$bot = PinterestBot::create();


//$resp = $bot->user->register('email1@gmail.com', 'password', 'name1', 22, "UK"); // i got error
$resp = $bot->user->register('email2@gmail.com', 'password', 'name2'); // works


echo var_export($resp);
print_r($bot->getLastError());
`

**Comment by seregazhuk** [comment]
Oh, I see. There is a mistake in documentation. Age and region are in wrong order. I'll fix it.
Here is the right sample of code:

```php
$resp = $bot->user->register('email1@gmail.com', 'password', 'name1', "UK", 22); 
```
