### ISSUE TITLE
seems like my server IP gets blocked by Pinterest after using $bot->pins->create() 

### ISSUE THREAD

**Issue by hafizzia** [seregazhuk/php-pinterest-bot#169]
$bot->pins->create() works first time, it only creates about 30+ pins and then it stops working, seems like my server IP gets blocked by pinterest. 
I need to create bulk Pins to my Pinterest account.
any idea, how to create large number of pins?

**Comment by seregazhuk** [comment]
Hi, @hafizzia  
This library is not API calls, it is a bot. So try to behave as a real person. Don't be too aggressive creating or commenting pins. Put timeouts between creations. Don't put spam comments or links on them. Try to use different useragent for you account with:

```php
$bot->getHttpClient()->setOptions([
    CURLOPT_USERAGENT => 'Your_User_Agent',
]);
```
