### ISSUE TITLE
$bot->boards->info($username, $board) doesn't search for specific board

### ISSUE THREAD

**Issue by truffolone** [seregazhuk/php-pinterest-bot#183]
Hello,
I can't find a single board with the $bot->boards->info($username, $board) since he is just getting all the user boards in a single array response ignoring the $board param.

it seems like the 'slug' param in the request is not correctly handled by the pinterest endpoint

**Comment by seregazhuk** [comment]
Hi @truffolone 
Yes, the method worked wrong, it was wrong endpoint: `resource/BoardsResource/get/` instead of `resource/BoardResource/get` (board, without **s**).
I've fixed, update to get the latest changes.

**Comment by truffolone** [comment]
Thank you a lot, I couldn't find the API docs for Pinterest you are using so I couldn't fix it myself, now it is working :)
