### ISSUE TITLE
is there any plan to provide invite function?

### ISSUE THREAD

**Issue by rajenpal033** [seregazhuk/php-pinterest-bot#185]
Hello @seregazhuk ,

I am using this for a while and really liked it! 
I noticed that there is currently no options to invite people, will there be any chance to get it in near future?

Thanks.

**Comment by seregazhuk** [comment]
Hi, @rajenpal033 
Yes, the next release will come with the ability to reset passwords and invitations by email. I think it will be done on Monday.

**Comment by rajenpal033** [comment]
Thanks for your information, but it seems to be many functions for pins, boards, pinners, search etc. not working getting blank response. is there any reason?
Thanks.

**Comment by seregazhuk** [comment]
Can you give an example, what functions don't work?

**Comment by rajenpal033** [comment]
$bot->pins->info(pintId);
$bot->pins->search('wedding'); (this was working few hours ago)
$bot->pins->comment(pintId, 'nice one!');
and almost other functions from pins, boards as in like, repin etc. and the strange this is even the search is not working. But it's not like all are's working, some like user->profile, boards->forUser these are working fine. I just modified one of your file to save and fetch cookie, in CurlHttpClient.php file as following:
`protected function initCookieFile($username)
    {
        $mainDir = dirname(__FILE__).DIRECTORY_SEPARATOR.'data'.DIRECTORY_SEPARATOR.$username;
        if(!is_dir($mainDir)){
            mkdir($mainDir, 0755);
        }
        if(empty($username)) {
            return tempnam($mainDir, self::COOKIE_PREFIX);
        }

        $cookieName = self::COOKIE_PREFIX . $username;
        $cookieFilePath = $mainDir . DIRECTORY_SEPARATOR . $cookieName;
        
        if (!file_exists($cookieFilePath)) {
            touch($cookieFilePath);
        }

        return $cookieFilePath;
    }`
Let me know.
Thanks in advance.

**Comment by seregazhuk** [comment]
1) If you use FILE, there is no such constant in php, try to use __FILE__
2) If out have your own FILE constant, I think your $mainDir doesn't have permissions and bot can't save cookie files.

**Comment by seregazhuk** [comment]
update to the latest release (4.13.0) and you can send invites like this:
```php
$bot->user->invite($email);
```

To change cookies storage path you can use this method:

```php
$bot->getHttpClient()->setCookiesPath($customPath);
```

**Comment by rajenpal033** [comment]
Thanks @seregazhuk
