### ISSUE TITLE
Search not working 

### ISSUE THREAD

**Issue by sumandey121** [seregazhuk/php-pinterest-bot#189]
<?php
require('../vendor/autoload.php'); 

use seregazhuk\PinterestBot\Factories\PinterestBot;

$bot = PinterestBot::create();

// login
$result=$bot->user->login('username', 'password',false);

if(!$result) {
    echo $bot->getLastError();
    die();
}

print_r($bot->pins->search('wedding', 2));

?>

it returns Generator Object ( )

**Comment by seregazhuk** [comment]
Hi @sumandey121
Search works correctly. It should return Generator object. Try this to fetch all results at once:
```php
$res = iterator_to_array($bot->pins->search('wedding', 2));
print_r($res);
```

or use `foreach` loop:
```php
foreach($bot->pins->search('wedding', 2) as $pin) {
...
}
```
