### ISSUE TITLE
How to get a user followed me or not ?

### ISSUE THREAD

**Issue by sumandey121** [seregazhuk/php-pinterest-bot#192]
Userinfo function return

Array
(
    [impressum_url] => 
    [last_name] => Bardhan
    [domain_verified] => 
    [following_count] => 245
    [image_medium_url] => https://s-media-cache-ak0.pinimg.com/avatars/ibardhan_1420212276_75.jpg
    [like_count] => 4
    [image_xlarge_url] => https://s-media-cache-ak0.pinimg.com/avatars/ibardhan_1420212276_280.jpg
    [full_name] => Indrojit Bardhan
    [image_small_url] => https://s-media-cache-ak0.pinimg.com/avatars/ibardhan_1420212276_30.jpg
    [id] => 544161704884351899
    [first_name] => Indrojit
    [domain_url] => 
    [explicitly_followed_by_me] => 
    [location] => 
    [indexed] => 1
    [is_partner] => 
    [type] => user
    [image_large_url] => https://s-media-cache-ak0.pinimg.com/avatars/ibardhan_1420212276_140.jpg
    [board_count] => 1
    [username] => ibardhan
    [repins_from] => Array
        (
            [0] => Array
                (
                    [username] => JBL316
                    [repins_from] => Array
                        (
                        )

```
                [image_medium_url] => https://s-media-cache-ak0.pinimg.com/avatars/JBL316_1416014134_75.jpg
                [full_name] => jbl
                [image_small_url] => https://s-media-cache-ak0.pinimg.com/avatars/JBL316_1416014134_30.jpg
                [id] => 344314471419780089
            )

    )

[verified_identity] => Array
    (
    )

[twitter_url] => 
[facebook_url] => https://www.facebook.com/indrojit.bardhan.5
[has_showcase] => 
[follower_count] => 0
[pin_count] => 2
[about] => 
[show_impressum] => 
[has_board] => 1
[website_url] => 
[blocked_by_me] => 
```

)

**Comment by seregazhuk** [comment]
You can check if user exists in your followers:
```php
foreach($bot->pinners->followers('yourUserName') as $follower)
{
    // ...
}
```

**Comment by hhitch** [comment]
I was looking for the same answer but it seems like that's an awful lot of followers to iterate through in order to find out if someone is following you or not - it could take a half hour if the account has a lot of followers. Is there an easier way to do it by any chance?

**Comment by seregazhuk** [comment]
@hhitch I see. Yes, it looks weird :(

Actually, you can call `$bot->pinners->info('username')` and then use `explicitly_followed_by_me` flag in the returning array.

**Comment by seregazhuk** [comment]
I think I'll add a helper method for it.

**Comment by hhitch** [comment]
good question, to be honest I'm not sure if they show that the way Twitter does. On the person's following page you would show up but I guess the order depends on how long ago that person followed you - they seem to list in cronological order. I see you labelled it with easy pick - I hope it is! Thanks man - great lib :)

**Comment by seregazhuk** [comment]
@hhitch actually it is impossible to get such information as a single request :( You have to manually loop through all the followers. 
P.S. if you will find where it is available on the site, then I think it will be possible to implement in bot.
