### ISSUE TITLE
Pins search return empty result

### ISSUE THREAD

**Issue by woozyfr** [seregazhuk/php-pinterest-bot#196]
Pins search return empty result.
My code (before it worked): 
`
require_once("vendor/autoload.php");
use seregazhuk\PinterestBot\Factories\PinterestBot;
$bot = PinterestBot::create();
var_dump($bot->pins->search("car", 10));
`

My Result  : 
`object(Generator)#11 (0) {
}
`

**Comment by seregazhuk** [comment]
It is not empty result, it is generator object. [It is said](https://github.com/seregazhuk/php-pinterest-bot#search) in the docs, how to use search methods.
Use `foreach`loop or `iterator_to_array` function.
