### ISSUE TITLE
profile image upload not work

### ISSUE THREAD

**Issue by bowodesign** [seregazhuk/php-pinterest-bot#218]
Hello sir
just wonder does the profile image still work?
because i try few time, the profile image cant uploaded

thank you

**Comment by seregazhuk** [comment]
Hi @bowodesign ,
I've just checked, and it works. Here is my code:
```php
$bot = PinterestBot::create();
if(!$bot->auth->login('login', 'pass')) {
    var_dump($bot->getLastError());
    die('login failed');
}

$bot->user->profile(['profile_image' => 'logo.jpg']);
var_dump($bot->getLastError());
```

What is your output of the `getLastError()`?

**Comment by bowodesign** [comment]
omg sorry this is my false
iam using old script that i forked lol
you right its work
so sorry
