### ISSUE TITLE
how to use proxy

### ISSUE THREAD

**Issue by jandreas0210** [seregazhuk/php-pinterest-bot#219]
Hi 
bit confuse how to use proxy in this script
for example i want to register - > login -> create board then logout, how should I do to make all that 4 step using proxy, if using standard step maybe i can use just like this (cmiiw) but how when i should use proxy, how to do it?

$bot->auth->register('youremail@gmail.com', 'password', 'Name');
$result = $bot->auth->login('mypinterestlogin', 'mypinterestpassword');
$bot->boards->create('name', 'description');
$bot->auth->logout();

thank you

**Comment by seregazhuk** [comment]
Hi, @jandreas0210 
Bot uses Curl library to handle requests. So you can specify proxy like this:
```php
$bot->getHttpClient()->setOptions([
    CURLOPT_PROXY => 'xx.xx.xxx.xx:xxxx',
    CURLOPT_PROXYTYPE => CURLPROXY_HTTP // or CURLPROXY_SOCKS5,
    CURLOPT_USERAGENT => 'Your_User_Agent',
]);
```

**Comment by jandreas0210** [comment]
Hi @seregazhuk can u give sample script integrated that code 
still confuse where should i put that code, is it before that 4 code above i write or after it or where?

thank you

**Comment by seregazhuk** [comment]
Put it before you login, for example:
```php
require('vendor/autoload.php'); 

use seregazhuk\PinterestBot\Factories\PinterestBot;

$bot = PinterestBot::create();

$bot->getHttpClient()->setOptions([
    CURLOPT_PROXY => 'xx.xx.xxx.xx:xxxx',
    CURLOPT_PROXYTYPE => CURLPROXY_HTTP // or CURLPROXY_SOCKS5,
    CURLOPT_USERAGENT => 'Your_User_Agent',
]);
$bot->auth->login('mypinterestlogin', 'mypinterestpassword');
```

**Comment by jandreas0210** [comment]
Ok got it !

thank you for your help @seregazhuk :)
