### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by misterkek** [seregazhuk/php-pinterest-bot#231]
Used this code:
```
require('vendor/autoload.php'); 
use seregazhuk\PinterestBot\Factories\PinterestBot;

$bot = PinterestBot::create();
$login = $bot->auth->login('login', 'pass'); //return true

$a=$bot->pins->feed(100);
$b=$bot->pins->search('batman',100);

print_r($a); //It returns an array of strange data, which are not similar to the correct data.
print_r($b); //It returns an array of strange data, which are not similar to the correct data.
```

![screenshot_1](https://cloud.githubusercontent.com/assets/16016364/21471705/cb9167da-cacb-11e6-82b1-023626350fc5.png)

**Comment by seregazhuk** [comment]
Hi, @misterkek 
these methods return a `Traversable` object. You can iterate it with a `foreach` loop, or use `toArray()` method to get results as array:
```php
$a=$bot->pins->feed(100)->toArray();
$b=$bot->pins->search('batman',100)->toArray();
```
It is done becouse Pinterest doesn't return all results at once.

**Comment by misterkek** [comment]
@seregazhuk Спасиб, братишка

**Comment by misterkek** [comment]
@seregazhuk дошли руки проверить...
всё равно не работает почему-то, просто пустой массив выводит..
причем не только в этом методе, а даже при попытке просмотреть названия бОрдов

**Comment by seregazhuk** [comment]
@misterkek , а ты скачал последнюю версию 5.1.6?
Вот сейчас проверил:
```php
$bot = PinterestBot::create();
$bot->auth->login('login', 'pass');

$a=$bot->pins->feed(100)->toArray();
$b=$bot->pins->search('batman',100)->toArray();

```
В обоих случаях вернулись данные

**Comment by misterkek** [comment]
Да, последнюю вроде скачал: вбил заново `composer require seregazhuk/pinterest-bot`  и перезалил файлы.
Аккаунт корректно из браузера работает, нигде не написано, что забанен.

Интересный момент: попробовал намеренно исказить данные для авторизации, а он при любых значениях возвращает `true`.

P.S. Попробовал на другом сервере - там работает. Похоже, IP забанили.
