### ISSUE TITLE
Search returning only 25 results

### ISSUE THREAD

**Issue by MaurieF** [seregazhuk/php-pinterest-bot#238]
I am using the script as per your readme file to search for pins and whether I write to an array or iterate over the generator object, the maximum I can get is 25.
For example:
`$results0 = $bot->pins->search('kitchens', 0)->toArray();
echo count($results0). "<br/>"; //25
$results20 = $bot->pins->search('kitchens', 20)->toArray();
echo count($results20). "<br/>"; //20
$results50 = $bot->pins->search('kitchens', 50)->toArray();
echo count($results50). "<br/>";// 25
$results100 = $bot->pins->search('kitchens', 100)->toArray();
echo count($results100). "<br/>";  //25`
I wonder what I'm doing wrong?

**Comment by seregazhuk** [comment]
Hi, @MaurieF 
Fixed in version 5.2.2, please update.

**Comment by MaurieF** [comment]
Hi, @seregazhuk 
How do I check the version?
I installed via composer just two days ago...
Do I just reinstall with composer?

**Comment by MaurieF** [comment]
Its OK thanks. I have worked it out.
Thanks for your help...
