### ISSUE TITLE
Как получить список пинов и количество лайков и количество досок для пина с определенного сайта?

### ISSUE THREAD

**Issue by nepohex** [seregazhuk/php-pinterest-bot#242]
Добрый день! 

Как с помощью вашего бота получить список пинов по запросу вот такого вида 
https://www.pinterest.com/source/giphy.com/

И отсюда нужно получить количество досок для каждого пина с данного сайта, далее некое подобие вот такого запроса который отображает общее количество пинов для данного URL пина https://api.pinterest.com/v1/urls/count.json?&url=http://giphy.com/gifs/colbertlateshow-stephen-colbert-late-show-l44QiBOm1VJ97BOhO

**Comment by seregazhuk** [comment]
@nepohex добрый день!
Получить пины по определенному сайту можно так:
```php
$pins = $bot->pins->fromSource('giphy.com')->toArray();
// вернет сразу все, может долго выполняться, пока не получит от апи все пины
$pins = $bot->pins->fromSource('giphy.com')->take(10)->toArray(); // только первые 10
```

По кол-ву досок для пина не знаю, можно попробовать выбрать инфу по пину и посмотреть там в массиве, может что-то будет похожее:

```php
$info = $bot->pins->info(271975264977139509);
```

**Comment by nepohex** [comment]
Спасибо, помогло!
В массиве по пинам отдается количество 
$pins[6]['aggregated_pin_data']['aggregated_stats']['saves'] сохранений в доски
$pins[6]['aggregated_pin_data']['aggregated_stats']['likes'] количество лайков

**Comment by seregazhuk** [comment]
Отлично! я даже и не знал, что там такое есть)
