### ISSUE TITLE
MultiThreading - мультипоточность.

### ISSUE THREAD

**Issue by nepohex** [seregazhuk/php-pinterest-bot#243]
Привет! Еще раз хочу поблагодарить за столь прекрасный и полезный код который меня выручил ) 

Подскажите, сложно ли / возможно ли добавить возможность работать мультипоточно через прокси и разные аккаунты? Скорости очень-очень не хватает - даже для API запросов, получается на обработку около 1.5 сек, а когда нужно прошерстить тысячи запросов - уходят часы. 

Не стоит ли это в планах разработки, и если да, то возможно вас простимулировать дополнительно $? :)

Также хотелось бы функцию типа random rotate user agent с привязкой к конкретному аккаунту и конкретной проксе под каждый аккаунт.

**Comment by seregazhuk** [comment]
@nepohex , привет! спасибо)
Что касается прокси и юзер-агента, то это настраивается, в [документации это есть](https://github.com/seregazhuk/php-pinterest-bot#use-proxy).
Мультипоточность - это уже мало относится к самой библиотеке, это скорее - то, как ее будут использовать, так что это точно не планируется.
Все что касается прокси, юзерагента и прочих кастомных настроек, библиотека дает возможность все это настроить, но дальнейшее использование - это уже задача разработчика, который будет использовать библиотеку.
Единственное, я бы хотел предостеречь, от слишком агрессивного использования в нескольких потоков, да даже в одном потоке. Pinterest жестко банит за такое. Только он заподозрит, что это не реальный пользователь (слишком часто лайки ставятся, коментарии или пины создаются) - будет бан.
