### ISSUE TITLE
PHP Fatal error:  Call to a member function isEmpty() on boolean

### ISSUE THREAD

**Issue by nepohex** [seregazhuk/php-pinterest-bot#249]
Доброго дня! Работаю не первую неделю под Windows/Openserver и все работает отлично. 
Под Centos + Vesta , PHP 5.6.30 (cli) (как и под Windows) вылазит ошибка. Версия бота "seregazhuk/pinterest-bot": "^**5.2.3**" под Windows , а Centos - последняя версия **5.2.4**.

PHP Fatal error:  Call to a member function isEmpty() on boolean in /home/admin/web/11.12.76.157/public_html/vendor/seregazhuk/pinterest-bot/src/Helpers/Pagination.php on line 144

При исполнении такого кода:
```
        $related = $bot->pins->related('56224695328753842', 500); //Не важно какой pin
        foreach ($related as $pin) {
//mynewbiecode
}
```
Добегает до определенного пина (например, до 478) и выдает ошибку т.к. чаще всего related < 500 , хотя под Windows на старой версии "бегает" даже если всего 10 пинов.

**Comment by seregazhuk** [comment]
Привет! да, была проблема, падает на последнем ответе от Pinterest. Исправил в версии 5.2.5 Обновляйся и заработает)
