### ISSUE TITLE
How to avoid banned from Pinterest

### ISSUE THREAD

**Issue by Minhnguyendhth8b** [seregazhuk/php-pinterest-bot#253]
I wrote a code to register account and it works at first but after 30 minutes i can't register any new account from that. The bot is alway return : 
"Your account has been suspended. Learn more at https://www.pinterest.com/_/_/about/acceptable-use-policy/"
- So my question is how to avoid banned from Pinterest ? 
Now i can't register anymore on my vps, but i still can register on my local , what different ?

**Comment by seregazhuk** [comment]
Hi @Minhnguyendhth8b 
I think you were too aggressive making pins or comments. Try to put some `sleep()` calls, so you will behave like a real person and not a bot, creating hundreds of pins in a minute.
