### ISSUE TITLE
get pins of a board

### ISSUE THREAD

**Issue by doctorbinsibar** [seregazhuk/php-pinterest-bot#259]
i want to get pins of a specified board.
Is this possible i dont see any way for this ?!

**Comment by seregazhuk** [comment]
Yes, of course. 
Get all pins for board by id (returns [Pagination](https://github.com/seregazhuk/php-pinterest-bot#pagination) object):

```php
$pins = $bot->boards->pins($boardId)->toArray();

// or this

foreach ($bot->boards->pins($boardId) as $pin) {
    // ...
}
```
