### ISSUE TITLE
API_ERROR. how do I fix it?

### ISSUE THREAD

**Issue by danie234** [seregazhuk/php-pinterest-bot#265]
when I run this script, the results that appear are API_ERROR. how do I fix it?

**Comment by seregazhuk** [comment]
@danie234 any code examples?

**Comment by danie234** [comment]
This code:
<?php

require __DIR__ . '/vendor/autoload.php';

use seregazhuk\PinterestBot\Factories\PinterestBot;

$bot = PinterestBot::create();

$result = $bot->auth->login('email', 'password');

if (!$result) {
    echo $bot->getLastError();
    die();
}
if ($bot->auth->isLoggedIn()) {
    echo"success";
}

**Comment by danie234** [comment]
link : https://isocialmax.com/pinterest/follow.php

**Comment by seregazhuk** [comment]
Looks like wrong credentials? Have you tried to login via browser with this login/pass?
I have just released a new version with more verbose error messages. Try to update (v5.3.2) and see what is the error now.

**Comment by danie234** [comment]
Thanks friend, it work and cool :)

**Comment by seregazhuk** [comment]
I'm glad I could help 👍
