### ISSUE TITLE
Cann't login and no last error

### ISSUE THREAD

**Issue by rabintang** [seregazhuk/php-pinterest-bot#267]
hi, i can't login using pinterest bot and getLastError returns empty.
can you help me to find out what happened?
`$username = "***";                                               
$passwd = "***";                                                           
$bot = PinterestBot::create();                                                     
// 1. proxy                                                                        
//$bot->getHttpClient()->useProxy("112.74.133.239", "82");                         
                                                                                   
// 2. Login                                                                        
$result = $bot->auth->login($username, $passwd);                                   
if (!$result) {                                                                    
  echo "last error:".$bot->getLastError()."\n";                                    
  die();                                                                           
}                                                                                  
if ($bot->user->isBanned()) {                                                      
  die("Account $username has been banned!\n");                                     
}                                                                                  
//                                                                                 
// Get lists of your boards                                                        
$boards = $bot->boards->forUser('user');                                      
var_dump($boards);`

**Comment by seregazhuk** [comment]
Hi, @rabintang 
Have you tried different credentials? Can you login with these credentials in your browser?

**Comment by rabintang** [comment]
yes, i have tried other accounts and it also failed. i can login by my browser.

**Comment by seregazhuk** [comment]
very strange, does this solve the problem?

```php
$result = $bot->auth->login('mypinterestlogin', 'mypinterestpassword', false);
```

**Comment by rabintang** [comment]
@seregazhuk no, it also failed. i run in other machines and get the same problems.
it was working at my first installation, but when i try again in second day, it failed.

**Comment by seregazhuk** [comment]
@rabintang have you tried bot without proxy? it looks like problem with proxy or bot cannot create cookies

**Comment by rabintang** [comment]
i run it in US machine, then it works. maybe it is caused by proxy.
thx for you good job!
