### ISSUE TITLE
Fatal error: Response.php on line 112

### ISSUE THREAD

**Issue by fudepita** [seregazhuk/php-pinterest-bot#272]
Hello. I'm having a Issue.
 can you help me?

This sample code run. 
require '../vendor/autoload.php';
use seregazhuk\PinterestBot\Factories\PinterestBot;
$bot = PinterestBot::create();
$result = $bot->auth->login('id', 'pass');
if (!$result) {
echo $bot->getLastError();
die();
}

result:
Fatal error: Can't use method return value in write context in /php-pinterest-bot/src/Api/Response.php on line 112

**Comment by seregazhuk** [comment]
Hi,  Bot requires PHP 5.5 or higher. Upgrade your php version
