### ISSUE TITLE
only 1 result from $bot->boards->search('cats', 50);

### ISSUE THREAD

**Issue by anarchoi** [seregazhuk/php-pinterest-bot#281]
No matter what i do i get only 1 result with this code. What's wrong ?

$searchresults = $bot->boards->search('cats', 50);
print_r($searchresults);

foreach($searchresults as $board); {
print_r($board);
}

**Comment by seregazhuk** [comment]
Maybe it is because you have a semi-column right after `foreach`?

**Comment by seregazhuk** [comment]
Oh, this is my mistake too. I'll fix it in the documentation.

**Comment by anarchoi** [comment]
Thanks for the fast reply. Can't believe i didn't see the semi-column haha that was an easy fix. There was no PHP error displayed so i didn't realize. Thanks so much for this code !
