### ISSUE TITLE
Filename cannot be empty in Cookies.php on line 48 

### ISSUE THREAD

**Issue by razza-guhl** [seregazhuk/php-pinterest-bot#282]
Hi,

I'm running a simple script to get boards by a specific user. 

```
<?php
require('vendor/autoload.php'); 
use seregazhuk\PinterestBot\Factories\PinterestBot;

$bot = PinterestBot::create();
$boards = $bot->boards->forUser("pinterest");
?>

```
Since today i'm getting this error:

> Warning: file(): Filename cannot be empty in [..]\htdocs\github\vendor\seregazhuk\pinterest-bot\src\Helpers\Cookies.php on line 48
> Warning: Invalid argument supplied for foreach() in [..]\htdocs\github\vendor\seregazhuk\pinterest-bot\src\Helpers\Cookies.php on line 48
> 
> Warning: file(): Filename cannot be empty in [..]\htdocs\github\vendor\seregazhuk\pinterest-bot\src\Helpers\Cookies.php on line 48
> Warning: Invalid argument supplied for foreach() in [..]\htdocs\github\vendor\seregazhuk\pinterest-bot\src\Helpers\Cookies.php on line 48

Any suggestions?

Thank you!

**Comment by seregazhuk** [comment]
Hi, @razza-guhl 
Please, update to version 5.3.11.
Maybe your script has no permissions to create files in system temporary directory.

**Comment by razza-guhl** [comment]
Thanks for fixing. Version 5.3.11. dont throw that error.

> Maybe your script has no permissions to create files in system temporary directory.

I cant tell. There were no system changes, today this error suddenly appeared. Using Windows 7 / XAMPP / PHP 5.6 Environment.

Which permission should be checked in case of creating temp files?

**Comment by razza-guhl** [comment]
Sorry, another thing:

Repinning doenst work. I dont know if there is correlation with the "Cookie.php"-error.
here is the code and the output.

```
$bot = PinterestBot::create();
$bot->auth->login("user", "pass", false);

if ( $bot->auth->isLoggedIn() ) {
    echo "logged in: yes";
}
else {
	echo "logged in: no";
}

echo "<br>";

if ( $bot->user->isBanned() ) {
    echo "banned: yes";
}
else {
	echo "banned: no";
}

$rePin = $bot->pins->repin("1234pinid56789", "1234boardid5678");

$pinterest_error_connect = $bot->getLastError();
echo "<br>";
echo $pinterest_error_connect;
```
returns error from bot:

> logged in: yes
> banned: no
> Authorization failed.

I double/trible checked the account. Manual repinning (with browser) is working, Account is not banned.

**Comment by seregazhuk** [comment]
Yes, I think it is cookies issue.
Try this code to find out your system temp folder:

```php
echo sys_get_temp_dir();
```

Or your can customize directory for cookies like this:
```php

$bot = PinterestBot::create();
$bot->getHttpClient()->setCookiesPath('path_to_your_folder');
```

**Comment by razza-guhl** [comment]
Thanks for your advice. Found my problem.

My temp-folder was some kind of full. It had enough free space, but there were a lot of files (also pinXXXX.tmp files) in it. I cleaned it up and the script is working again.

Now i'm using the cookie-remove-method in the script.

`$bot->getHttpClient()->removeCookies();`
