### ISSUE TITLE
Autoload Missing

### ISSUE THREAD

**Issue by thechacal** [seregazhuk/php-pinterest-bot#285]
Hello Sergey,

require __DIR__ . '/vendor/autoload.php';

Where the autoload archive?Directory "vendor" doesn't exist mate.

Best

**Comment by seregazhuk** [comment]
Hi, @thechacal 
When you install library via [composer](composer.org], it creates a `vendor` directory with the autoloading file in it. Try to use composer for managing your php dependencies.
