### ISSUE TITLE
error cant login after update

### ISSUE THREAD

**Issue by doctorbinsibar** [seregazhuk/php-pinterest-bot#287]
Fatal error: Uncaught seregazhuk\PinterestBot\Exceptions\InvalidRequest: Error calling seregazhuk\PinterestBot\Api\Providers\User::login method. Method login does'n exist. in /home/ftp8/public_html/pinterest/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Core/ProviderWrapper.php:48 Stack trace: #0 /home/ftp8/public_html/pinterest/profiler_.php(43): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->__call('login', Array) #1 {main} thrown in /home/ftp8/public_html/pinterest/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Core/ProviderWrapper.php on line 48

this is the part to the script:
/public_html/pinterest/vendor/seregazhuk/pinterest-bot/src/Factories

but on the Script it says:
use seregazhuk\PinterestBot\Factories\PinterestBot;

anybody can help ?

**Comment by doctorbinsibar** [comment]
this wont work.before update everything worked fine.

**Comment by seregazhuk** [comment]
Hi, @doctorbinsibar 
You have been using an old version. Since version 5, the api has changed, take a look at the [documentation](https://github.com/seregazhuk/php-pinterest-bot#quick-start)

**Comment by doctorbinsibar** [comment]
no i have updated to the newest version.
Thats the reason why i get this error message.

**Comment by doctorbinsibar** [comment]
This the Latest Error !
Is this because of the Server Settings ?

> 
Fatal error: Uncaught Error: Call to undefined function seregazhuk\PinterestBot\Helpers\finfo_open() in /home/ftp8/public_html/pinterest/vendor/seregazhuk/pinterest-bot/src/Helpers/FileHelper.php:20 Stack trace: #0 /home/ftp8/public_html/pinterest/vendor/seregazhuk/pinterest-bot/src/Api/Request.php(297): seregazhuk\PinterestBot\Helpers\FileHelper::getMimeType('3.jpg') #1 /home/ftp8/public_html/pinterest/vendor/seregazhuk/pinterest-bot/src/Api/Request.php(312): seregazhuk\PinterestBot\Api\Request->buildFilePostData('-------------59...') #2 /home/ftp8/public_html/pinterest/vendor/seregazhuk/pinterest-bot/src/Api/Request.php(285): seregazhuk\PinterestBot\Api\Request->makeHeadersForUpload() #3 /home/ftp8/public_html/pinterest/vendor/seregazhuk/pinterest-bot/src/Api/Request.php(267): seregazhuk\PinterestBot\Api\Request->getContentTypeHeader() #4 /home/ftp8/public_html/pinterest/vendor/seregazhuk/pinterest-bot/src/Api/Request.php(111): seregazhuk\PinterestBot\Api\Request->getDefaultHttpHeaders() #5 /home/ftp8/public_html/pinter in /home/ftp8/public_html/pinterest/vendor/seregazhuk/pinterest-bot/src/Helpers/FileHelper.php on line 20

**Comment by seregazhuk** [comment]
Yes, that's the reason. You have updated to the newest version but use old syntax. 
This is example from the docs:
```php
require('vendor/autoload.php'); 

use seregazhuk\PinterestBot\Factories\PinterestBot;

$bot = PinterestBot::create();

// Login
$bot->auth->login('mypinterestlogin', 'mypinterestpassword');
```

**Comment by seregazhuk** [comment]
To fix the latest error you should install and enable php fileinfo extension.
