### ISSUE TITLE
Edit Pins won't edit repins

### ISSUE THREAD

**Issue by codingmusician** [seregazhuk/php-pinterest-bot#288]
The method to edit pins seems to always try to edit the link of the pin, which you're not allowed to do on a repin.  This is what I did to make it work:
`public function edit($pindId, $description = '', $link = false, $boardId = false)`
`    {`
`        $requestOptions = [`
`            'id'          => $pindId,`
`            'description' => $description`
`        ];`
`        if($link !== false){`
`            $requestOptions["link"] = $link;`
`        }`
`        if($boardId !== false){`
`            $requestOptions["board_id"] = $boardId;`
`        }`

`        return $this->post($requestOptions, UrlBuilder::RESOURCE_UPDATE_PIN);`
`    }`

**Comment by seregazhuk** [comment]
@codingmusician , thank you for your feedback. Fixed in v5.4.2!
