### ISSUE TITLE
Issue with unfollow

### ISSUE THREAD

**Issue by msternik** [seregazhuk/php-pinterest-bot#30]
First of all, thanks very much for the library, everything has been working great for me apart for unfollow functionality. I use it as in the readme:

$bot->pinners->unfollow($userId);

However the user is not being unfollowed. I checked the error and I am getting:

[code] => INVALID_HTTP_METHOD_FOR_RESOURCE_METHOD
    [target] => None
    [http_status] => 400

Any idea why this could happen?

Thanks a lot!

**Comment by seregazhuk** [comment]
They have changed their base API url, so every POST method seemed to faile. I fixed it, update for new release
