### ISSUE TITLE
pinterest-bot have nodejs version ?

### ISSUE THREAD

**Issue by Restry** [seregazhuk/php-pinterest-bot#300]
hi @seregazhuk you are awesome !

Is there a nodejs implementation version ?

thanks :)

**Comment by seregazhuk** [comment]
Hi, @Restry ! Thank you) No, sorry, but I don't have enough node experience to implement the same library, so only PHP version is available.

**Comment by Restry** [comment]
Thanks for your response.
Your php bot it's also wonderful. 
I'm from China . my country gov was disabled to visit Pinterest site . We cannot look that nice pics . 
I want to break that . But my php experience it's not good 
Do u have any similar experience with php? Use your service to deploy a shell to a US-based server. So I can use the Pinterest service without restriction

Would you Guide me a right direction?

Thanks

**Comment by Restry** [comment]
I also have a php question . When I'm running the shell mode use php -a.  And run the code by line and line 

require('vendor/autoload.php'); 
use seregazhuk\PinterestBot\Factories\PinterestBot;
$bot = PinterestBot::create();

It's error , PinterestBot not found . Seems like it's not found the library . 
Can I run the code in php cli like that ?

**Comment by seregazhuk** [comment]
In README file there are links to blog posts with some common use cases of the library. To use this library you have to use PHP dependencies manager [Composer](https://getcomposer.org). It will install the library and create a `vendor/autoload.php` file.
