### ISSUE TITLE
Pin activity when not logged in.

### ISSUE THREAD

**Issue by MaurieF** [seregazhuk/php-pinterest-bot#305]
Hi @seregazhuk  ,
_$bot->pins->activity($pinId)_ works fine when logged in.
I would like to get the recent activity for a pin when not logged in.
Is there any way to do that?
Cheers,
Maurie

**Comment by seregazhuk** [comment]
Hi, @MaurieF 
No, Pinterest doesn't allow this. It returns `Authentication failed.` error.
