### ISSUE TITLE
Create a public board not working

### ISSUE THREAD

**Issue by huuvu1109** [seregazhuk/php-pinterest-bot#310]
Hi @seregazhuk ,

It seems that $bot->boards->create('Name', 'Description'); $bot->topics->pins($oneTopicToRepin , 40)->toArray();  doesn't work anymore in the newest version if we use the Proxy or Sock (it works well if we don't use proxies). Can you please check this.

Thanks!

**Comment by huuvu1109** [comment]
Hi @seregazhuk , 

I just test again, my socks have problem when I tested yesterday. Now, using socks working well. The remaining problem now is that if I use a proxy (CURLOPT_PROXYTYPE => CURLPROXY_HTTP,), the function $bot->boards->create('Name', 'Description'); doesn't work.

**Comment by seregazhuk** [comment]
Hi, @huuvu1109 , only `boards->create()` doesn't work or everything becomes broken with proxy? I think it is proxy related issue.

**Comment by huuvu1109** [comment]
Hi @seregazhuk ,

I just change the proxy, and it works with the new proxy.  But it is a really weird bug for the old proxy! For the old proxy, I can login , search ,...  but CAN NOT  use boards->create(), no error returned but no board created.

So, I will change the proxy to solve the problems. Thanks!

**Comment by huuvu1109** [comment]
Hi @seregazhuk , 

A longtime ago, we can get the information "pin_join" which return the text in the rectangle. It seems that it doesn't work in the newest version? Can you please check. Thanks!

$related = $bot->pins->related('83527768070255703'); 
foreach ($related as $pin) {
    if($pin['id'] == 355784439289886021) {
        print_r($pin['pin_join']); die();
    }
}

![9cd4905e-1141-11e7-9229-1db23538a7e3](https://user-images.githubusercontent.com/9253443/30066995-d596479a-9259-11e7-95c2-63c4dea1de61.png)

**Comment by seregazhuk** [comment]
Hi, @huuvu1109 
It looks like some pins have this field and some not:
```php
$related = $bot->pins->related('83527768070255703');
foreach ($related as $pin) {
    if(isset($pin['pin_join'])) {
        print_r($pin['pin_join']); die();
    }
}
```

**Comment by huuvu1109** [comment]
Hi @seregazhuk , I just check again. The return object for $bot->pins->related and $info = $bot->pins->info(1234567890) contains the property "pin_join". However,  there are no 'pin_join' property  for $bot->pins->search("new york") . 

Is this because Pinterest doesn't return  "pin_join" property when we search, or the bot doesn't support it?  Thanks!


foreach($bot->pins->search("new york")->toArray()  as $onePinInfo)
{	
	echo $onePinInfo['id']  . "\r\n";
	
	 if(isset($onePinInfo['pin_join'])) {
		print_r($onePinInfo['pin_join']); die();
	}

		
}

**Comment by seregazhuk** [comment]
I think that it is Pinterest issue, they don't return this field on search.
![4f9b14a046](https://user-images.githubusercontent.com/9959761/30277844-9fe6707c-9711-11e7-9955-7b05386345fc.jpg)
