### ISSUE TITLE
How to improve curl speed? 

### ISSUE THREAD

**Issue by morimorsin** [seregazhuk/php-pinterest-bot#311]
Hi, how can I get much faster API results?

Right now
@$info = $bot->pins->info($pinId);

and

$bot->pins->related($pinId, 20);

the average time was 2.64 s

Please help me, Could you give me a tips?

**Comment by seregazhuk** [comment]
Hi, @morimorsin 
I think it depends on your connection. I've tested it and for me that average value is 0-1 seconds.
