### ISSUE TITLE
Interests: category_type main and non-board

### ISSUE THREAD

**Issue by razza-guhl** [seregazhuk/php-pinterest-bot#314]
Hi,

Its not really an issue/bug but i have a question to the interests method. In your Readme there is an explaination about interests:

_1. Get a list of main categories. Required bot to be logged in:_

`$categories = $bot->interests->main();`

_2. Get category info by name (can be taken from main()):_

`$info = $bot->interests->info("gifts");`

The second one is not clear to me. How do you get the interest "gifts"? The info-method returns that this has category_type of "non-board". 

```
Array
(
    [images] => Array
        (
            [45x] => Array
                (
                    [url] => http://i.pinimg.com/categories/gifts-1384730624-45x.jpg
                    [width] => 45
                    [height] => 45
                )

        )

    [category_type] => non_board
    [type] => category
    [name] => Gifts
    [key] => gifts
)
```
While the output of "main()" just returns "main" category_types. So, i dont unterstand how you found the interest "gifts" with the usage of "main()" method.

Thank you

**Comment by seregazhuk** [comment]
Hi, @razza-guhl 
Sorry for late response. It looks like Pinterest has changed interests, that were returned as *main*
