### ISSUE TITLE
boards->info and specialchars ä, ö, ü

### ISSUE THREAD

**Issue by razza-guhl** [seregazhuk/php-pinterest-bot#315]
Hi,

I have issues with german specialchars (ä, ö ,ü ...). boards->info shows no results.

`$info = $bot->boards->info($username, 'Käsefondue' )`

API\Providers\Boards.php
Line 97:
```
protected function formatBoardName($board)
{
   return strtolower(str_replace(' ', '-', $board));
}
```
strtolower cannot convert such characters. In my case mb_strtolower should be used instead.

`mb_strtolower( str_replace(' ', '-', $board) , 'UTF-8' )`

Is there a way to solve this problem?

**Comment by seregazhuk** [comment]
Hi, @razza-guhl 
Thanks for your feedback! Fixed in version 5.5.5.
