### ISSUE TITLE
Getting Pin with search query using API or scraping Data??

### ISSUE THREAD

**Issue by shaileshsitestrokes** [seregazhuk/php-pinterest-bot#317]
I have a one question.
I need pins of specific search keyword .
I am getting pins with your code but i don't understand this is scraping or using API.
Beacause i havn't inserted my accesstoken anywhere.

**Comment by seregazhuk** [comment]
Hi, @shaileshsitestrokes 
Behind the hood it makes the same AJAX calls, as your browser does. So, in some sort it uses scraping, not public API.
