### ISSUE TITLE
Help PHP :)

### ISSUE THREAD

**Issue by ymongo** [seregazhuk/php-pinterest-bot#319]
Hi there, 

I may be missing a thing. I just dont't get how to launch a an example script? I have everything properly installed: Wamp server, Composer, downloaded the project files. When I run in cmd php *path/example_file.php* I have an error saying it's impossible to find some files from the require line. It shows a messy path string with / and at some point \ between folders names.  

Well. How does the script work? How do you launch it? Thanks for some help :)

**Comment by seregazhuk** [comment]
Hi, @ymongo 
Try to use 
`require __DIR__ . '/../vendor/autoload.php';`
instead of 
`require __DIR__ . '/vendor/autoload.php';`
