### ISSUE TITLE
Pin Search Results

### ISSUE THREAD

**Issue by MaurieF** [seregazhuk/php-pinterest-bot#322]
Hi,
I'm searching for pins (not logged in), with
$bot->pins->search('cats',10)->toArray();

Pin ID results for that are:
252201647863208831
8514686775072665
145944844155153075
330944272603353865
332914597439969006
449937819008782673
536350636856458419
310466968052721511
559994534906079563
478789004120875229

That's fine, but the results are not the same as when I visit a url:
eg: https://www.pinterest.com/search/pins/?q=cats or https://www.pinterest.co.uk/search/pins/?q=cats
The Pin ID results for that are:

624311567063856823
79727855883923036
574912708672373615
479985272777123714
624030092088930655
571535008947429703
283023157811165688
282741682835647022
640285271994209864
414823815667990946

I'm pretty sure that in the past the results did match (i.e. PinBot results and the URL search)
While the URL results will change across time, the PinBot results stay the same ..

I am using Version 554 of the library.
Any thoughts?
Cheers,
Maurie

**Comment by seregazhuk** [comment]
Hi, @MaurieF 
Looks like Pinterest now allows to search only if you are logged in.

**Comment by MaurieF** [comment]
Thanks Seregazhuk,
I'll try that.
pins->search still returns data, but it is the "explore" page results.
