### ISSUE TITLE
People Search .....pinners->search('query')

### ISSUE THREAD

**Issue by MaurieF** [seregazhuk/php-pinterest-bot#324]
Hi Seregazhuk,
Just noticed that the pinners/search query is returning an error.
I am using version 557 of the library.
For Example:
$bot->pinners->search('cats',10)->toArray(); previously gave the expected result.
It now gives an array which looks  like this:
Array
(
    [0] => 
    [1] => 
    [2] => Array
        (
        )

    [3] => 
    [4] => 
    [5] => 
    [6] => Array
        (
        )

    [7] => 
    [8] => 
    [9] => 
    [10] => 
    [11] => 
    [12] => 
    [13] => 
)

If I do a foreach on a pagination object, the result is blank.
Wondering what I m doing wrong, since this query used to work fine...
Cheers,
Maurie

**Comment by seregazhuk** [comment]
Hi, @MaurieF 
Looks like Pinterest has closed its search. Now it is available only if you are logged in. Can you try to log in and then search?

**Comment by MaurieF** [comment]
Hi @seregazhuk ,
Initially, logging in did not work either, but now its working when logged in.
Thanks for your help.

**Comment by seregazhuk** [comment]
To prevent misunderstanding why `search()` returns empty results, I'm going to update the bot and it will throw an exception when being not logged in you try to search.

**Comment by huuvu1109** [comment]
@seregazhuk : I think you should not throw exception or only throw exception if search for people. The reason is that it is still possible to search without logging if you search for pins (instead of people). 

If someone just want to search for pins, they can search with  both options: logged in or without logged in Because the returned result if logged in and without logged in is different. The returned result is personalized for each pinners based on what they are follow, like, comments ...

**Comment by seregazhuk** [comment]
@huuvu1109 Can you provide a link where I can search for pins in a browser without logging in? I've researched their site and it looks like I should be logged in to use search.

**Comment by huuvu1109** [comment]
@seregazhuk : 

+ https://www.pinterest.com/search/pins/?q=cat&rs=typed&term_meta[]=cat%7Ctyped

you can just copy this link in an incognito browser, it still return results.

+ https://www.pinterest.com/search/people/?q=cat&rs=typed&term_meta[]=cat%7Ctyped

While for this link, they don't return Pinners, they just return Pins if you are not logged in

**Comment by huuvu1109** [comment]
https://www.pinterest.com/search/pins/?q=cat&rs=typed&term_meta[]=cat%7Ctyped

==>and  because of  with this link, the returned result if you logged in and not logged in are  different. So, I think you should support both cases.

**Comment by seregazhuk** [comment]
@huuvu1109 I see, thank you for links! Yes, I'll change behavior only for `pinners->search()`, and `pins`functionality will stay the same.

**Comment by seregazhuk** [comment]
In version 5.5.8 bot throws `AuthRequired` exception when calling `pinners->search()` without being logged in.
