### ISSUE TITLE
syntax error, unexpected 'function' (T_FUNCTION)

### ISSUE THREAD

**Issue by shaileshsitestrokes** [seregazhuk/php-pinterest-bot#325]
Hello seregazhuk,
I am getting syntax error in Response.php file.
when i run "pin_parser.php" file on my server its showing below error.
Parse error: syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in phppinterest/vendor/seregazhuk/pinterest-bot/src/Api/Response.php on line 5

why this happen at my end.
when i try to run this file in xampp then its working but on my domain/server its showing error.

please help me

Thanks

**Comment by seregazhuk** [comment]
Hi @shaileshsitestrokes 
Library requires PHP version 5.6+ and it looks like your server doesn't meet this requirement
