### ISSUE TITLE
Problems with repins

### ISSUE THREAD

**Issue by kitesurf** [seregazhuk/php-pinterest-bot#326]
Trying your example for like, comments and repin, just with my own boards, I'm running all the time in the same error:
PHP Fatal error:  Uncaught Error: Call to undefined function seregazhuk\PinterestBot\Api\Providers\mb_strtolower() in /Pinterest-bot/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Boards.php:99
Stack trace:
#0 /Pinterest-bot/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Boards.php(85): seregazhuk\PinterestBot\Api\Providers\Boards->formatBoardName('Love beach')
#1 [internal function]: seregazhuk\PinterestBot\Api\Providers\Boards->info('myusername', 'Love beach')
#2 /Pinterest-bot/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Core/ProviderWrapper.php(44): call_user_func_array(Array, Array)
#3 /Pinterest-bot/check_repins.php(8): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->__call('info', Array)
#4 {main}
  thrown in /Pinterest-bot/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Boards.php on line 99

**Comment by seregazhuk** [comment]
Hi, @kitesurf 
Fixed in version 5.5.9, please update

**Comment by kitesurf** [comment]
Thanks for fixing.. but still having errors by only testing the example for like and repins.

PHP Fatal error:  Uncaught seregazhuk\PinterestBot\Exceptions\AuthRequired: Error calling seregazhuk\PinterestBot\Api\Providers\Pins::like method. You must log in before. in /Progys/Pinterest-bot/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Core/ProviderWrapper.php:66
Stack trace:
#0 /Pinterest-bot/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Core/ProviderWrapper.php(42): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->checkMethodForLoginRequired('like')
#1 /Pinterest-bot/check_repins.php(13): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->__call('like', Array)
#2 {main}
  thrown in /Pinterest-bot/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Core/ProviderWrapper.php on line 66

**Comment by seregazhuk** [comment]
It's throws an exception, because you are not logged in. Use `$bot->auth->login('mypinterestlogin', 'mypinterestpassword')` with your credentials.

**Comment by kitesurf** [comment]
I'm trying just your example from [http://sergeyzhuk.me/2017/03/30/build-pinterest-bot-with-php-comments-and-repins/](url)
here is my code:
`<?php
require __DIR__ . '/vendor/autoload.php';
use seregazhuk\PinterestBot\Factories\PinterestBot;
$comments = ['Nice!', 'Cool!', 'Very beautiful!', 'Amazing!'];
$bot = PinterestBot::create();
$bot->auth->login('daniel@kite-mallorca.com', 'here_my_pw');

$board = $bot->boards->info('kite_mallorca', 'Kitesurfing on Mallorca');

$pins = $bot->pins->search('beach')->toArray();
foreach($pins as $pin) {
    // put like
    $bot->pins->like($pin['id']);
    // repin to our board
    $bot->pins->repin($pin['id'], $board['id']);
    // write a comment
    $comment = $comments[array_rand($comments)];
    $bot->comments->create($pin['id'], $comment);
}`

As you can see, it's just the final script from your blog

**Comment by seregazhuk** [comment]
And you get `AuthRequired` exception? If so, it is an issue with authentication. Try to debug it:

```php
$result = $bot->auth->login('daniel@kite-mallorca.com', 'here_my_pw');
if(!$result) {
    echo $bot->getLastError(); die();
}
```

It will display an error, if authentication fails.

**Comment by kitesurf** [comment]
I'm so sorry, using the wrong PW. I'm adding DB check if liked or repined and trying to login to Pinterest with the mysql PW... Anything is right!!!
