### ISSUE TITLE
Board sections

### ISSUE THREAD

**Issue by razza-guhl** [seregazhuk/php-pinterest-bot#327]
Hello,

is it possible to include the new feature "Sections" under the Board-functions?

Source: blog.pinterest.com/en/new-way-organize-your-ideas-pinterest

**Comment by seregazhuk** [comment]
Hi, @razza-guhl 
Yes, I think on Monday will be a new release with this feature.

**Comment by seregazhuk** [comment]
@razza-guhl Done! Please update library to version `5.6.0`. [Here](https://github.com/seregazhuk/php-pinterest-bot#board-sections) is the documentation.

**Comment by razza-guhl** [comment]
Thank you @seregazhuk. You are doing amazing work here.
