### ISSUE TITLE
Pagination only returns first 25 pins

### ISSUE THREAD

**Issue by creativeprogramming** [seregazhuk/php-pinterest-bot#330]
Even if i use take(0) and ->skip properly i cannot get over the 25th element of a ->feed() or ->fromSource() obtained Pagination object

**Comment by seregazhuk** [comment]
Hi @creativeprogramming 
Try this:
```php
$feed = $bot->pins->feed()->take(0);
// or 
$feed = $bot->pins->feed(0);
```
