### ISSUE TITLE
Reset getLastError()

### ISSUE THREAD

**Issue by razza-guhl** [seregazhuk/php-pinterest-bot#333]
Is it possible to cleanup the results in getLastError() output?

I have chain of different actions, that are based on each other. If getLastError() returns something, then something else should be do within the same instance. 
But the output of getLastError() always returns the previous (error-state) results, although the current action is okay. So i need a reset/cleanup here.
(Hope you understand the use-case)

**Comment by seregazhuk** [comment]
Yes, I've understood your use-case. Actually, now it is impossible. But each method returns results or a boolean value. You can check what your action has returned. Does it solve your problem?

**Comment by razza-guhl** [comment]
Checking return value would be ok. But $bot->boards->create() always return false, even if the board could be created (at least, on my side)

**Comment by seregazhuk** [comment]
That's strange. I've just checked, and it returns `true` when board was created, otherwise - `false`. Need more details or code snippet.

**Comment by razza-guhl** [comment]
There was something wrong on my side. It's working as expected.
Sorry for the confusion
