### ISSUE TITLE
sendMessage is not working properly.

### ISSUE THREAD

**Issue by barankhan** [seregazhuk/php-pinterest-bot#334]
When I try to send message using.

$bot->inbox->sendMessage("739927551186610300", 'Hello Boy!!!')

It returns true but message is not delivered to the user. It worked couple of times but now it stopped working. I also have checked for ban but the following method returns false.

$bot->user->isBanned()

**Comment by barankhan** [comment]
Following is the curl response of sendMessage method. As per educated guess there is some problem with csrf token. 

    object(stdClass)[23]
      public 'request_identifier' => string '577545007294' (length=12)
      public 'resource_data_cache' => 
        array (size=0)
          empty
      public 'module' => 
        object(stdClass)[15]
          public 'html' => string '<div data-reactcontainer><div data-reactroot="" data-reactid="1" data-react-checksum="2044412707"><div data-reactid="2"><div class="App AppBase" data-reactid="3"><div data-reactid="6"><div class="" data-reactid="7"><div data-test-id="header" class="_0 _3i _2m _11 _3w _2g _2i _2l _5e" style="z-index:671;" data-reactid="8"><div data-reactid="9"><div class="_0 _3i _2m _2 _i" data-reactid="10"><div class="_0 _3i _2m _11 _3w _2 _3e _6k _7f _h" data-reactid="11"><div '... (length=17727)
          public 'tree' => 
            object(stdClass)[21]
      public 'resource_response' => 
        object(stdClass)[22]
          public 'data' => null
          public 'error' => null
      public 'page_info' => 
        object(stdClass)[19]
          public 'meta' => 
            object(stdClass)[20]
              public 'description' => string 'Discover recipes, home ideas, style inspiration and other ideas to try.' (length=71)
              public 'naver-site-verification' => string '449f5675319d27f34f90dc99f63f1892389589fc' (length=40)
              public 'og:description' => string 'Discover recipes, home ideas, style inspiration and other ideas to try.' (length=71)
              public 'og:image' => string 'https://s.pinimg.com/images/facebook_share_image.png' (length=52)
              public 'og:title' => string 'Pinterest' (length=9)
              public 'og:type' => string 'website' (length=7)
              public 'og:url' => string 'https://uk.pinterest.com/resource/ConversationsResource/create/' (length=63)
              public 'pinterest' => string 'nohover' (length=7)
              public 'theme-color' => string '#bd081c' (length=7)
              public 'twitter:app:android' => string 'com.pinterest' (length=13)
              public 'twitter:app:id:ipad' => string '429047995' (length=9)
              public 'twitter:app:id:iphone' => string '429047995' (length=9)
              public 'twitter:card' => string 'summary_large_image' (length=19)
              public 'twitter:site' => string '@pinterest' (length=10)
          public 'title' => string 'Pinterest' (length=9)
      public 'client_context' => 
        object(stdClass)[18]
          public 'unauth_id' => string '82d758870c30497e993e969c20153631' (length=32)
          public 'origin' => string 'https://uk.pinterest.com' (length=24)
          public 'browser_locale' => string 'en-US' (length=5)
          public 'user_agent_platform' => string 'other' (length=5)
          public 'facebook_token' => null
          public 'is_authenticated' => boolean true
          public 'csp_nonce' => string 'jVEHKhvTsS' (length=10)
          public 'triggerable_experiments_hash' => string '712195087764382452' (length=18)
          public 'sterling_on_steroids_ldap' => null
          public 'browser_version' => string '55.0.2883' (length=9)
          public 'app_shell' => boolean false
          public 'parent_request_identifier' => null
          public 'deep_link_action' => null
          public 'nag_browser_unsupported' => boolean false
          public 'is_tablet_agent' => boolean false
          public 'visible_url' => string '' (length=0)
          public 'react_only' => null
          public 'triggerable_experiments' => 
            object(stdClass)[17]
              public 'search_pfy_quiz_results_pins' => string 'control' (length=7)
              public 'ads_lift_holdout_tjxadvlevel_q3_2017' => string 'enabled' (length=7)
              public 'ads_hf_interaction_items_query_holdout' => string 'rollout' (length=7)
              public 'ads_lift_holdout_modcloth_4q2017' => string 'enabled' (length=7)
              public 'ads_inter_page_cache_manas_candidates' => string 'rollout' (length=7)
              public 'smartfeed_topical_feed_en_negative_feedback_filter' => string 'enabled_v3' (length=10)
              public 'ads_global_holdout_2017_h2' => string 'prod' (length=4)
              public 'pure_react_python_resources_pin_2' => string 'enabled' (length=7)
              public 'simple_search_scope_v2' => string 'enabled_day_0' (length=13)
              public 'ads_lift_holdout_google_pixel_us_q4_2017' => string 'enabled' (length=7)
              public 'ads_lift_holdout_wrangler_q4_2017' => string 'enabled' (length=7)
              public 'quick_promote_rewrite' => string 'enabled' (length=7)
              public 'sterling_always_on_campaign' => string 'enabled' (length=7)
              public 'sterling_cpv_metrics' => string 'enabled' (length=7)
              public 'link_stock_signal_filter_exp_v2' => string 'treatment' (length=9)
              public 'ads_hf_retrieval' => string 'ads_hf_retrieval_lsh_query_5' (length=28)
              public 'guided_search_experiments' => string 'promote_ads_queries' (length=19)
              public 'ads_lift_holdout_waitrose_uk_q4_2017' => string 'enabled' (length=7)
              public 'ads_lift_holdout_walt_disney_world_usa__seasonal_vid_usa_q1_q2_2017_unvalidated' => string 'enabled' (length=7)
              public 'ads_lift_holdout_smashbox_q4_2017' => string 'enabled' (length=7)
              public 'ads_lift_holdout_thefword_q2_2017' => string 'enabled' (length=7)
              public 'ads_lift_holdout_kitchenaid_q3_2017' => string 'enabled' (length=7)
              public 'sterling_react_migration' => string 'enabled' (length=7)
              public 'us_open_umbrella_pin' => string 'auth_closeup' (length=12)
              public 'ads_lift_holdout_thd_q3_2017' => string 'enabled' (length=7)
              public 'sterling_conversion_tags_summary' => string 'enabled' (length=7)
              public 'server_render_grid_open_board' => string 'enabled_16' (length=10)
              public 'ads_lift_holdout_nestle_uk_q317' => string 'enabled' (length=7)
              public 'ads_lift_holdout_purina_q118' => string 'enabled' (length=7)
              public 'ads_lift_holdout_amazon_home_q4_2017' => string 'control' (length=7)
              public 'ads_lift_holdout_acura_2017q1' => string 'enabled' (length=7)
              public 'server_render_grid_open_klp' => string 'enabled_16' (length=10)
              public 'nux_skip_tp_home_feed_improve' => string 'nux_skip_tp_home_feed_improve_use_rec_service' (length=45)
              public 'smartfeed_topical_feed_en_nux' => string 'smartfeed_topical_feed_in_ph_curated_topics_exp' (length=47)
              public 'ads_lift_holdout_walmart_tab_q1_2018' => string 'enabled' (length=7)
              public 'web_composer_save_from_website' => string 'enabled' (length=7)
              public 'ads_lift_holdout_amazon_echo_q4_2017' => string 'enabled' (length=7)
              public 'ads_lift_holdout_target_fallstyle_q3_2017' => string 'enabled' (length=7)
              public 'smartfeed_topical_feed_en_nux_pixie_relevance_filtering' => string 'enabled_curated' (length=15)
              public 'ads_lift_holdout_mead_johnson_q4_2017' => string 'enabled' (length=7)
              public 'nux_extension_skip_if_installed' => string 'control' (length=7)
              public 'pinnability_rtc_coldstart_fix_v2' => string 'prod' (length=4)
              public 'sterling_pinner_list' => string 'enabled' (length=7)
              public 'ads_lift_holdout_yooxocl_q4_2017' => string 'control' (length=7)
              public 'ads_ppa_rp_whitelist' => string 'converse_control' (length=16)
              public 'did_it_image_pipeline_experiment' => string 'enabled' (length=7)
              public 'ads_lift_holdout_intel_brandlift_q4_2017' => string 'enabled' (length=7)
              public 'sterling_bulk_v2' => string 'enabled' (length=7)
              public 'ads_lift_holdout_nestle_tollhouse_q3_2017' => string 'enabled' (length=7)
              public 'ads_lift_holdout_asda_uk_q417' => string 'enabled' (length=7)
              public 'ads_lift_holdout_dm3_q4_2017' => string 'enabled' (length=7)
              public 'ads_lift_holdout_franks_q1_2018' => string 'control' (length=7)
              public 'ads_related_pins_relevance_threshold' => string 'v3_rge3_mfl_010' (length=15)
              public 'search_related_queries_stories_pixie_service' => string 'enabled' (length=7)
              public 'sterling_canada' => string 'enabled' (length=7)
              public 'partner_source_page_email' => string 'control' (length=7)
              public 'ads_lift_holdout_bofa_q2_2017' => string 'enabled' (length=7)
              public 'title_exp_klp_v2' => string 'enabled_5_0' (length=11)
              public 'ads_hf_pixie_query' => string 'top_1_100_100' (length=13)
              public 'ads_shopping_two_tap_qf' => string 'control_v1' (length=10)
              public 'sterling_async_report_download' => string 'enabled' (length=7)
              public 'web_search_food_apply_color' => string 'enabled' (length=7)
              public 'bypass_cctld_register_email' => string 'control' (length=7)
              public 'web_pure_react_limited_login2' => string 'enabled' (length=7)
              public 'ads_lift_holdout_rimmeluk_q3_2017' => string 'enabled' (length=7)
              public 'ads_lift_holdout_starz_q12017' => string 'enabled' (length=7)
              public 'sterling_campaign_placement' => string 'enabled' (length=7)
              public 'copytune_new_user_recommendations_subject_line_v2' => string 'variant_seven' (length=13)
              public 'ads_search_early_dedup' => string 'v6_control' (length=10)
              public 'recommendation_p2b_pixie_migration' => string 'enabled' (length=7)
              public 'sterling_bulk_editor_async_validation' => string 'enabled' (length=7)
              public 'bypass_cctld_login_gplus' => string 'enabled' (length=7)
              public 'creation_remove_likes_phase_2' => string 'enabled_rollout' (length=15)
              public 'test_javery_auth_experiment' => string 'enabled' (length=7)
              public 'ads_lift_holdout_feeding_america_q4_2017' => string 'enabled' (length=7)
              public 'ads_lift_holdout_wishupon_q12017' => string 'enabled' (length=7)
              public 'ads_lift_holdout_pgr_q4_2017' => string 'enabled' (length=7)
              public 'ads_lift_holdout_rimmel_q1_2017_internalbrandlift' => string 'enabled' (length=7)
              public 'ads_lift_holdout_kate_spade_q4' => string 'enabled' (length=7)
              public 'ads_lift_holdout_badmoms_q3_2017' => string 'control' (length=7)
              public 'ads_lift_holdout_zappos_q4_2017' => string 'enabled' (length=7)
              public 'hashtag_feeds_from_realpin' => string 'enabled_realpin_recent_and_top' (length=30)
              public 'ads_lift_holdout_vauxhall_q3_2017' => string 'enabled' (length=7)
              public 'web_native_content_profile' => string 'enabled2' (length=8)
              public 'ads_lift_holdout_staples_q4_2017' => string 'enabled' (length=7)
              public 'ads_lift_holdout_orientaltrading_q3_2017' => string 'enabled' (length=7)
              public 'ads_lift_holdout_landrover_q2_2017' => string 'enabled' (length=7)
              public 'ads_lift_holdout_daddyshome2_q3_2017' => string 'enabled' (length=7)
              public 'ads_lift_holdout_chasesaph_q4_2017' => string 'enabled' (length=7)
              public 'unauth_pin_cache' => string 'control' (length=7)
              public 'sterling_react_billing_page' => string 'enabled' (length=7)
              public 'ads_android_mweb_one_tap_login_landing' => string 'one_button2' (length=11)
              public 'sterling_expressive_interests' => string 'enabled' (length=7)
              public 'ads_lift_holdout_ulta_shopping_campaign_internal_test_q3_2017' => string 'control' (length=7)
              public 'fbc_parent' => string 'enabled_rewards' (length=15)
              public 'ads_shopping_separate' => string 'v2_launch' (length=9)
              public 'ads_lift_holdout_chasepay_q4_2017' => string 'enabled' (length=7)
              public 'web_follow_feed_button' => string 'enabled' (length=7)
              public 'ads_lift_holdout_visa_internalbrandlift_q2_2017_2' => string 'enabled' (length=7)
              public 'ads_lift_holdout_starz_q3_2017' => string 'enabled' (length=7)
              public 'promote-app-install-pins' => string 'control' (length=7)
              public 'ads_lift_holdout_ralph_lauren_q317_uk' => string 'enabled' (length=7)
              public 'ads_enable_pacing_for_reserved_cinematic' => string 'enabled' (length=7)
              public 'ads_related_pins_visual_query_2' => string '3_control' (length=9)
              public 'ads_targeting_match_later' => string 'enabled' (length=7)
              public 'ads_lift_holdout_wix_q3_2017' => string 'enabled' (length=7)
              public 'commerce_pin_matching' => string 'enabled_image' (length=13)
              public 'pinnability_multi_head_user_states_v1' => string 'prod' (length=4)
              public 'ads_lift_holdout_thestar_q4_2017' => string 'enabled' (length=7)
              public 'sterling_bid_video_campaign' => string 'enabled' (length=7)
              public 'partner_nux_copy' => string 'control' (length=7)
              public 'web_native_content_carousel' => string 'enabled' (length=7)
              public 'ads_autoplay_video' => string 'rollout' (length=7)
              public 'polaris_pfy_time_exp_v2' => string 'control' (length=7)
              public 'sterling_archive' => string 'enabled' (length=7)
              public 'ads_browsy_2' => string 'control' (length=7)
              public 'ads_hf_retrieval_qdfa_heatmap' => string 'annot_qdfa_heatmap_matching_and_scoring' (length=39)
              public 'ads_remove_utz_with_prior' => string 'enabled' (length=7)
              public 'sterling_show_audience_video_targeting' => string 'enabled' (length=7)
              public 'mweb_halloween_mode' => string 'enabled' (length=7)
              public 'sterling_form_default_bid3' => string 'enabled' (length=7)
              public 'unauth_lazy_import_fullpagesignup' => string 'control' (length=7)
              public 'ads_lift_holdout_homegoods_q22017' => string 'enabled' (length=7)
              public 'web_usm_lfv_low_res_images_lp' => string 'control' (length=7)
              public 'ads_log_plain_mobile_advertiser_id' => string 'enabled' (length=7)
              public 'ads_lift_holdout_canon_q22017' => string 'enabled' (length=7)
              public 'ads_lift_holdout_jared_q4_2017' => string 'enabled' (length=7)
              public 'ads_lift_holdout_simply_q3_2016' => string 'enabled' (length=7)
              more elements...
          public 'utm_campaign' => null
          public 'is_full_page' => boolean false
          public 'browser_type' => int 1
          public 'deep_link' => string '' (length=0)
          public 'is_amp' => boolean false
          public 'css_bundles' => 
            array (size=1)
              0 => string 'https://s.pinimg.com/webapp/style/common_desktop-d17b77451c8da1df1997f6a8f3c937bb.css' (length=85)
          public 'from_open_in_app_click' => null
          public 'real_ip' => string '203.128.16.109' (length=14)
          public 'is_bot' => string 'false' (length=5)
          public 'user_agent_platform_version' => null
          public 'invite_code' => null
          public 'request_host' => string 'uk.pinterest.com' (length=16)
          public 'locale' => string 'en-US' (length=5)
          public 'in_mobile_fork_exp' => boolean false
          public 'utm_medium' => null
          public 'placed_experiences' => null
          public 'is_open_experience' => boolean false
          public 'is_managed_advertiser' => boolean false
          public 'analysis_ua' => 
            object(stdClass)[16]
              public 'os_name' => string 'Mac OS X' (length=8)
              public 'app_type' => int 5
              public 'browser_name' => string 'Chrome' (length=6)
              public 'os_version' => string '10.12.2' (length=7)
              public 'browser_version' => string '55.0.2883' (length=9)
              public 'device_type' => null
              public 'device' => string 'Other' (length=5)
          public 'pure_react_render_error' => null
          public 'request_identifier' => string '577545007294' (length=12)
          public 'root_request_identifier' => null
          public 'mock_date' => null
          public 'seo_experiments' => 
            object(stdClass)[13]
          public 'pure_react' => boolean true
          public 'app_type' => int 5
          public 'active_experiments' => 
            object(stdClass)[14]
          public 'current_url' => string 'https://uk.pinterest.com/csrf_error/' (length=36)
          public 'is_retina' => boolean false
          public 'has_ads_api_access' => boolean false
          public 'user' => 
            object(stdClass)[25]
              public 'is_employee' => boolean false
              public 'phone_number' => null
              public 'phone_number_end' => string '' (length=0)
              public 'last_name' => string '' (length=0)
              public 'domain_verified' => boolean false
              public 'nags' => 
                array (size=0)
                  ...
              public 'image_medium_url' => string 'https://s.pinimg.com/images/user/default_75.png' (length=47)
              public 'has_password' => boolean true
              public 'image_xlarge_url' => string 'https://s.pinimg.com/images/user/default_280.png' (length=48)
              public 'full_name' => string 'Barankhan' (length=9)
              public 'unverified_phone_number_without_country' => string '' (length=0)
              public 'image_small_url' => string 'https://s.pinimg.com/images/user/default_30.png' (length=47)
              public 'gplus_url' => null
              public 'id' => string '826903318990229585' (length=18)
              public 'is_write_banned' => boolean false
              public 'first_name' => string 'Barankhan' (length=9)
              public 'domain_url' => null
              public 'facebook_timeline_enabled' => boolean false
              public 'facebook_id' => string '' (length=0)
              public 'connected_to_google' => boolean false
              public 'is_partner' => boolean false
              public 'unverified_phone_number' => null
              public 'type' => string 'user' (length=4)
              public 'email' => string 'barankhan@yahoo.com' (length=19)
              public 'image_large_url' => string 'https://s.pinimg.com/images/user/default_140.png' (length=48)
              public 'connected_to_yahoo' => boolean false
              public 'phone_country' => null
              public 'verified_identity' => 
                object(stdClass)[26]
                  ...
              public 'twitter_url' => null
              public 'facebook_url' => null
              public 'unverified_phone_country' => null
              public 'has_mfa_enabled' => boolean false
              public 'twitter_publish_enabled' => boolean false
              public 'resurrection_info' => null
              public 'push_package_user_id' => string '826903318990229585:MQv0ZGTom1ETng7qLhk11zWvxF0' (length=46)
              public 'facebook_publish_stream_enabled' => boolean false
              public 'connected_to_microsoft' => boolean false
              public 'gender' => string 'male' (length=4)
              public 'created_at' => string 'Mon, 15 Jan 2018 09:52:00 +0000' (length=31)
              public 'verified_domains' => 
                array (size=0)
                  ...
              public 'can_enable_mfa' => boolean true
              public 'username' => string 'barankhan9385' (length=13)
              public 'login_state' => int 1
              public 'website_url' => null
              public 'country' => string 'PK' (length=2)
          public 'deep_link_default' => string '' (length=0)
          public 'http_referrer' => string 'https://uk.pinterest.com/' (length=25)
          public 'path' => string '/csrf_error/' (length=12)
          public 'is_mobile_agent' => boolean false
          public 'site_type' => int 0
          public 'is_internal_ip' => boolean false
          public 'app_version' => string 'b6a524a' (length=7)
          public 'language' => string 'en' (length=2)
          public 'is_sterling_on_steroids' => boolean false
          public 'referrer' => null
          public 'user_agent_can_use_native_app' => boolean false
          public 'is_mdl_campaign_type_whitelisted' => boolean false
          public 'browser_name' => string 'Chrome' (length=6)
          public 'is_eligible_for_one_tap_sterling' => boolean false
          public 'user_agent' => string 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36' (length=120)
          public 'user_agent_is_ios_9_or_above' => boolean false
          public 'country' => string 'PK' (length=2)
          public 'error_template_path' => string 'templates/error.nunjucks' (length=24)
          public 'site_const' => 
            object(stdClass)[27]
              public 'PIN_MARGIN' => int 14
              public 'MAX_COLUMNS' => int 10
              public 'MIN_COLUMNS' => int 3
              public 'PRESENTER_BUTTON_MODULE_NAME' => string 'DropdownButton' (length=14)
              public 'PIN_WIDTH' => int 236
          public 'full_path' => string '/csrf_error/' (length=12)

**Comment by seregazhuk** [comment]
Hi, I've checked and it works. One notice here, when you are sending a message to unknown person Pinterest doesn't show your message. It suggests this person to create a contact with you. Only then you can send messages, see [Contact requests](https://github.com/seregazhuk/php-pinterest-bot#contact-requests)

**Comment by barankhan** [comment]
When first time i sent the message It showed the request and after accept it showed the message. It was working fine in start. but later it stopped working. I have showed the response of the curl request.

**Comment by barankhan** [comment]
It worked fine after i cleared the cookies.
