### ISSUE TITLE
Get Pins of Topics doesn't work

### ISSUE THREAD

**Issue by huuvu1109** [seregazhuk/php-pinterest-bot#335]
Hi @seregazhuk , 

Can you please check why $bot2->topics->pins() doesn't work in some cases. For example, for the topic "box-logo-hoodie" (https://www.pinterest.com/topics/box-logo-hoodie/) , the following code return nothing:
	
$bot2 = PinterestBot::create();
$pinsOfThese = $bot2->topics->pins("box-logo-hoodie")->toArray();
print_r($pinsOfThese);

***However, with other topics like $pinsOfThese = $bot2->topics->pins("apparel-design")->toArray();  everything works well.

Thanks!

**Comment by seregazhuk** [comment]
Hi, @huuvu1109 
Very strange, it returns `Interest not found.`. Any ideas are welcome, I can't find out the problem 😞

**Comment by seregazhuk** [comment]
@huuvu1109 I see. Can you please create a separate issue for it? and I'll fix it soon.
