### ISSUE TITLE
Problem when create pins from local driver

### ISSUE THREAD

**Issue by huuvu1109** [seregazhuk/php-pinterest-bot#337]
Hi @seregazhuk , 

One more strange problem is that when I tried:

$pinInfo = $bot->pins->create('image.jpg', $boardId, 'Pin description');

I expected that I will get a pin like this one: https://www.pinterest.com/pin/775463629560232207/ , which is showed that the pin is uploadeded by a user and the link behind is : https://user-images.githubusercontent.com . But, when I tried that, the link is: s3.amazonws.com, and when you click the pin, it download the image . You can try the bot with one local image and recognize these. It seems that Pinterest do something to filter the bot.

Thanks!

**Comment by seregazhuk** [comment]
@huuvu1109 
Fixed, try version `5.6.2`

**Comment by huuvu1109** [comment]
Hi @seregazhuk ,

Have you updated the code? I use composer require seregazhuk/pinterest-bot to get the new version, but it seems that the version is still 5.6. Can you please check?

 Thanks!

**Comment by seregazhuk** [comment]
Composer didn't update version. Try it now, it should work

**Comment by huuvu1109** [comment]
I see. It works well now. Thanks!
