### ISSUE TITLE
Не логинится с ошибкой "Sorry! Your request could not be completed."

### ISSUE THREAD

**Issue by nepohex** [seregazhuk/php-pinterest-bot#338]
Привет! Пытаюсь залогиниться $bot->auth->isLoggedIn() выдает TRUE , но $bot->getLastError() выдает ошибку "Sorry! Your request could not be completed." 

В браузере тоже не логинится под этим логин-паролем, с той же ошибкой, после ввода логин-пароля просто ничего не происходит кроме маленькой оповещалки http://prntscr.com/i2s54p , и не пускает внутрь.

2 момента:
1. Бот не должен писать что логин прошел $bot->auth->isLoggedIn()  == FALSE
2. Не знаешь что это за ошибка такая? Полагаю это какой-то бан аккаунта.

**Comment by seregazhuk** [comment]
Привет! Если ты раньше был залогинен, то бот в след раз не будет отправлять запрос на логин, а вместо этого воспользуется сохраненной кукой (чтобы уменьшить кол-во запросов, и больше походить на реального пользователя). Поэтому ` $bot->auth->isLoggedIn()` показывает лишь то, что у тебя установлена кука авторизации. Чтобы при логине принудительно отправить запрос на Pinterest попробуй так:

```php
$result = $bot->auth->login('mypinterestlogin', 'mypinterestpassword', false);
```

Для проверки что ты забанен используй `user->isBanned`:

```php
if ($bot->user->isBanned() {
    // You have ban
}
```

Если даже в браузере такое, может косяк на их стороне
