### ISSUE TITLE
Get all the boards I follow

### ISSUE THREAD

**Issue by delemore** [seregazhuk/php-pinterest-bot#345]
ATM it is not possible to get all the boards I follow. Please implement this. Thank you!!

**Comment by seregazhuk** [comment]
Looks like it is already implemented. Check the docs [here](https://github.com/seregazhuk/php-pinterest-bot/blob/master/docs/pinners.md#following-boardspinnersinterests).

**Comment by delemore** [comment]
Great Job. Thank you!
