### ISSUE TITLE
Get the number of pins per tag

### ISSUE THREAD

**Issue by huuvu1109** [seregazhuk/php-pinterest-bot#348]
Hi @seregazhuk , 

When you repin a pin, we can select a board to save the pin, then we can click Edit Description to change the description. In this step, if we type a tag (a word starting with #) , Pinterest will suggest a list of corresponding tags with the number of pins which each tag is used. You can see it in the following figure:

![image](https://user-images.githubusercontent.com/9253443/36334955-f9d964b2-137c-11e8-8ec9-40b4f4ffa56a.png)

Can you please also support this feature for the bot, I mean a function which take a tag as the input, and the output is the number of pins for that tag.

Thanks!

**Comment by seregazhuk** [comment]
Hi, @huuvu1109 
update to v5.6.6 and use [tags suggestions](https://github.com/seregazhuk/php-pinterest-bot/blob/master/docs/search.md#tags-suggestions)
