### ISSUE TITLE
Search for string within the pin array

### ISSUE THREAD

**Issue by ltiwana** [seregazhuk/php-pinterest-bot#349]
Hi, I am trying to perform a string search within the pin info array but it doesn't work for me. I am using the below function to perform a recursive array search. It works if I create my own array but doesn't work with pin info array.

`function in_array_r($needle, $haystack, $strict = false) {`
`    foreach ($haystack as $item) {`
`        // cast $item to string if numeric when doing weak comparison`
`        if( ! $strict && is_string( $needle ) && ( is_float( $item ) || is_int( $item ) ) ) {`
`            $item = (string)$item;`
`        }`
`        // ----------------------------------------------------------`
``
`        // Substring search`
`        if( is_string( $needle ) && is_string( $item ) && strpos( $item, $needle ) !== false ) {`
`            return true;`
`        }`
``
`        // ----------------`
` `
`        if (($strict ? $item === $needle : $item == $needle) || (is_array($item) && in_array_r($needle,` `$item, $strict))) {`
`            return true;`
`        }`
`    }`
``
`    return false;`
`}`

**Comment by seregazhuk** [comment]
Hi @ltiwana , I don't know how does your function relate to the library. Try to debug it yourself. Pin info is a simple array and doesn't change from any other PHP array.

**Comment by ltiwana** [comment]
I am looking for this functionally in my PHP script so that when I am searching for 100 pin for cybersecurity, I want to make sure the pin contains the word in it before I repin it to my board. Maybe there is another way to achieve this?

**Comment by ltiwana** [comment]
Any pointer will be awesome. I am very new to PHP.
