### ISSUE TITLE
Fatal Error When Trying to Do Auto Pin

### ISSUE THREAD

**Issue by flameblue59** [seregazhuk/php-pinterest-bot#351]
I get a problem when I tried to do auto pin from /examples directory
I have entered my login detail but I received this following error.

`Fatal error: Uncaught seregazhuk\PinterestBot\Exceptions\AuthRequired: Error calling seregazhuk\PinterestBot\Api\Providers\User::isBanned method. You must log in before. in /home/admin/ocicio/botsector/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Core/ProviderWrapper.php:66 Stack trace: #0 /home/admin/ocicio/botsector/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Core/ProviderWrapper.php(42): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->checkMethodForLoginRequired('isBanned') #1 /home/admin/ocicio/botsector/index.php(15): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->__call('isBanned', Array) #2 {main} thrown in /home/admin/ocicio/botsector/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Core/ProviderWrapper.php on line 66`

Could you please to check this? Here is my code.

```
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
require_once($_SERVER["DOCUMENT_ROOT"].'/botsector/vendor/autoload.php');

use seregazhuk\PinterestBot\Factories\PinterestBot;

$blogUrl = 'http://awasome-blog-about-cats.com';
$keywords = ['cats', 'kittens', 'funny cats', 'cat pictures', 'cats art'];

$bot = PinterestBot::create();
$bot->auth->login('myusername', 'mypassword');

if ($bot->user->isBanned()) {
    echo "Account has been banned!\n";
    die();
}

// get board id
$boards = $bot->boards->forUser('myusername');
$boardId = $boards[0]['id'];

// select image for posting
$images = glob('images/*.*');
if (empty($images)) {
    echo "No images for posting\n";
    die();
}

$image = $images[0];

// select keyword
$keyword = $keywords[array_rand($keywords)];

// create a pin
$bot->pins->create($image, $boardId, $keyword, $blogUrl);

// remove image
unlink($image);
```

**Comment by seregazhuk** [comment]
Hi @flameblue59 
I think there is a problem with your login. Try to debug it:

```php
$result = $bot->auth->login('mypinterestlogin', 'mypinterestpassword');

if (!$result) {
    echo $bot->getLastError();
    die();
}
```

**Comment by flameblue59** [comment]
Hi, it shows a blank page. There is no error.

**Comment by seregazhuk** [comment]
@flameblue59 can you login in a browser with the same credentials?

**Comment by flameblue59** [comment]
Yeah, I can log in in a browser.

**Comment by seregazhuk** [comment]
Don't know. May be something with cookies. The last try is to force login request instead of loading saved cookies. Try add third `false` parameter to `login()` call:

```php
$bot->auth->login('myusername', 'mypassword', false);
```

**Comment by flameblue59** [comment]
It is still the same, Here is my code

```
$bot = PinterestBot::create();
$result = $bot->auth->login('8cab@stidac.id', '******', FALSE);

if (!$result) {
    echo $bot->getLastError();
    die();
}

$boards = $bot->boards->forUser('8cab');
$boardId = $boards[0]['id'];

echo $boardId;
```

I am trying to var_dump $result and it return

> bool(false)

**Comment by seregazhuk** [comment]
Closed due to not enough information. Cannot reproduce the bug.

**Comment by ghost** [comment]
Same error.
1 year passed from the last comment.
Any progress, I hope so.
Thanks in advance.
