### ISSUE TITLE
Unable to see Comments array data in Pin array

### ISSUE THREAD

**Issue by ltiwana** [seregazhuk/php-pinterest-bot#361]
I was able to see the comments array in pins array, but it seems it isn't displayed anymore. 
```

Array

(
     [bookmark] => LT42OTM4Mzg1NjYzNzE4OTA4ODo1fDIxNzNhNzViMWEzNDhmMGIwN2RhNTRhMjU2YjcwODJjZTVkYzdiYWFmNzcyMjE2Zjg5NGMzOTVhNDZjMzAyOGM=
    [data] => Array
         (
         )

     [uri] => /v3/pins/69383650488493124/comments/
 )
```

**Comment by seregazhuk** [comment]
Can you show the code please?

**Comment by ltiwana** [comment]
here is my code:
`date_default_timezone_set('America/Toronto');`
`require __DIR__ . '/vendor/autoload.php';`
`use seregazhuk\PinterestBot\Factories\PinterestBot;`

`$bot = PinterestBot::create();`

`$pins = $bot->pins->search('security', 20)->toArray();`

`foreach($pins as $pin) {`
`print_r ($pin['comments']);`
`}`

**Comment by seregazhuk** [comment]
@ltiwana Looks like it is on Pinterest side. Their response doesn't contain comments data
<img width="1045" alt="comments" src="https://user-images.githubusercontent.com/9959761/37769932-c93f3170-2de3-11e8-801d-6cdc220cc5b1.png">

**Comment by ltiwana** [comment]
Oh okay, so there is no way to know if I have already commented on the pin.

**Comment by seregazhuk** [comment]
Update to version `5.6.9` and use [this code](https://github.com/seregazhuk/php-pinterest-bot/blob/master/docs/pins.md#get-list-of-comments).

**Comment by ltiwana** [comment]
Just tried again. Here is the error i get:

> PHP Fatal error:  Uncaught seregazhuk\PinterestBot\Exceptions\InvalidRequest: Error calling seregazhuk\PinterestBot\Api\Providers\Comments::getList method. Method getList does'n exist. in C:\Users\ltiwana\Documents\GitHub\php-pinterest-bot\vendor\seregazhuk\pinterest-bot\src\Api\Providers\Core\ProviderWrapper.php:48
> Stack trace:
> #0 C:\Users\ltiwana\Documents\GitHub\php-pinterest-bot\Test.php(93): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->__call('getList', Array)
> #1 {main}
>   thrown in C:\Users\ltiwana\Documents\GitHub\php-pinterest-bot\vendor\seregazhuk\pinterest-bot\src\Api\Providers\Core\ProviderWrapper.php on line 48

Here is my code:

```
date_default_timezone_set('America/Toronto');
require __DIR__ . '/vendor/autoload.php';
use seregazhuk\PinterestBot\Factories\PinterestBot;

$bot = PinterestBot::create();`
$pins = $bot->pins->search('cats', 100)->toArray();

foreach($pins as $pin) {
			
	$comments = $bot->comments->getList($pin['id'])->toArray();

	foreach($comments as $comment) {
		print_r ($comment);
		sleep (2);
	}
}
		
```

**Comment by seregazhuk** [comment]
Looks like you haven't updated to `5.6.9`

**Comment by ltiwana** [comment]
from changelog.md, it shows me the following comment:
```
# Change Log
All notable changes to this project will be documented in this file.

## v5.6.9 - 2018-03-21
### Added:
 - get comments for a specified pin
```
and pins.md has modify date of today 3/22/2018 12:56PM.

**Comment by seregazhuk** [comment]
I've just created an empty project, required the library and everything is ok 😕

**Comment by ltiwana** [comment]
I am setting it up on a new system from scratch. Hopefully, it works.

**Comment by seregazhuk** [comment]
@ltiwana does it work for you?

**Comment by ltiwana** [comment]
@seregazhuk this is fixed, and working on the new project. 

My problem was that I wanted to make sure that i don't end up with duplicate comments on the same pin. So I used the comment array to check if my name is under comments. Is there a better way to find that out?

**Comment by seregazhuk** [comment]
Close, because its not library issue, but Pinterest itself.
