### ISSUE TITLE
Proxy not working correct

### ISSUE THREAD

**Issue by saulacher** [seregazhuk/php-pinterest-bot#371]
When I am trying start to register/login with proxy it is not working correctly. I cant update Profile and make a repin when I am using proxy. I tried to debug it with this:
```
if($bot->getHttpClient()->usesProxy()) {
    echo "proxy";
}
```
But I get "true" each time even when I use not correct proxy host/port, so is it bug?

When I register/login without proxy everything ok. With VPN working fine too. Proxy is valid, I tried with several https and socks5.  You can try with my socks5:
185.118.66.215:39984 gilman06: vftloisf

**Comment by seregazhuk** [comment]
Hi! No, actually it is not a bug, it is not a *checker* for your proxy. It just returns `true` if you have specified *any* proxy. 
Under the hood it uses Curl library with the following settings: https://github.com/seregazhuk/php-pinterest-bot/blob/master/src/Api/CurlHttpClient.php#L301

**Comment by saulacher** [comment]
Thank you, but it does not work anyway. When i am registering without proxy - everything fine. With proxy - not working. Here is my code :
```
use seregazhuk\PinterestBot\Factories\PinterestBot;

$bot = PinterestBot::create();

$bot->getHttpClient()->setOptions([
    CURLOPT_PROXY => '185.118.66.215:39984',
    CURLOPT_PROXYTYPE => CURLPROXY_SOCKS5, // orCURLPROXY_SOCKS5,
    CURLOPT_PROXYUSERPWD => 'gilman06:vftloisf',

]);

$bot->auth->register('slitr56@gmail.com', '12475389', 'Sli');
$bot->auth->login("slitr56@gmail.com", "12475389", false);
$profile = $bot->user->profile();
echo $profile['username'];
```

and errors:

```
PHP Fatal error:  Uncaught exception 'seregazhuk\PinterestBot\Exceptions\AuthRequired' with message 'Error calling seregazhuk\PinterestBot\Api\Providers\User::profile method. You must log in before.' in /Users/ivangutnik/Desktop/pinterest/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Core/ProviderWrapper.php:66
Stack trace:
#0 /Users/ivangutnik/Desktop/pinterest/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Core/ProviderWrapper.php(42): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->checkMethodForLoginRequired('profile')
#1 /Users/ivangutnik/Desktop/pinterest/samplereg.php(21): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->__call('profile', Array)
#2 /Users/ivangutnik/Desktop/pinterest/samplereg.php(21): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->profile()
#3 {main}
  thrown in /Users/ivangutnik/Desktop/pinterest/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Core/ProviderWrapper.php on line 66
Fatal error: Uncaught exception 'seregazhuk\PinterestBot\Exceptions\AuthRequired' with message 'Error calling seregazhuk\PinterestBot\Api\Providers\User::profile method. You must log in before.' in /Users/ivangutnik/Desktop/pinterest/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Core/ProviderWrapper.php:66
Stack trace:
#0 /Users/ivangutnik/Desktop/pinterest/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Core/ProviderWrapper.php(42): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->checkMethodForLoginRequired('profile')
#1 /Users/ivangutnik/Desktop/pinterest/samplereg.php(21): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->__call('profile', Array)
#2 /Users/ivangutnik/Desktop/pinterest/samplereg.php(21): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->profile()
#3 {main}
  thrown in /Users/ivangutnik/Desktop/pinterest/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Core/ProviderWrapper.php on line 66
```

**Comment by seregazhuk** [comment]
Here is the error with your proxy: `Can\'t complete SOCKS5 connection to 2a07:14c0:0000:835b:0000:0000:0000:250d:54095. (5)`. If it works without proxy, may it is the problem with it, or something wrong with Curl settings. If you will find a bug, feel free to provide a PR with fix 👍

**Comment by seregazhuk** [comment]
@saulacher do you have any new feedback? Does your proxy work?

**Comment by saulacher** [comment]
Not working yet, but I think it is problem in the proxy. Pinterest banned most of public proxys and only high-quality elite private proxies can be used. I am planning run United States based VPS and i think always will be ok in this case. So thank you for your help, code working correct 👍
