### ISSUE TITLE
Bulk Delete Pin not work

### ISSUE THREAD

**Issue by liyuanzao** [seregazhuk/php-pinterest-bot#372]
I tried to trace the error, 

The error shows "Sorry, we can't delete some of your pins!" from last error info.

However, from the pinterest action, they have changed the board_id to source_url (username/boardname).

Maybe that's why it won't work.

**Comment by seregazhuk** [comment]
Sorry, can't reproduce. May be the reason is in some specific pin, as an error says.

**Comment by seregazhuk** [comment]
Closed due to now feedback
