### ISSUE TITLE
Full URL in Boards Pins

### ISSUE THREAD

**Issue by delemore** [seregazhuk/php-pinterest-bot#375]
Is it possible to get the full URL to every pin? Currently the API returns only the top level Domain to each pin.

**Comment by seregazhuk** [comment]
Hi, @delemore What do you mean by "full URL"?

**Comment by delemore** [comment]
@seregazhuk , I mean a URL like this:
https://edition.cnn.com/style/article/alcohol-cigarette-vintage-ads/index.html

Currently Board Pins Returns only: https://edition.cnn.com/

So my question is, if it's possible for you to Change your Code in that way it delivers the complete URL?

**Comment by seregazhuk** [comment]
Try this:

```php
$info = $bot->pins->info('366339750933822415');
echo $info['link'];
```

**Comment by delemore** [comment]
Great, that works. Thank you!
