### ISSUE TITLE
$bot->auth->isLoggedIn() works only if $bot->auth->login() was called

### ISSUE THREAD

**Issue by kolyalukin** [seregazhuk/php-pinterest-bot#379]
Auto login by cookie work only if i call $bot->auth->login() with particular username, password dont important, but i cannot call $bot->auth->login() without password argument

**Comment by seregazhuk** [comment]
Hi @kolyalukin 
I'm not sure what I've understood you correctly. So, what is the issue? How can I reproduce your problem?

**Comment by seregazhuk** [comment]
Yes, sure. Feel free to provide a pull request with a new method for cookie login 👍
