### ISSUE TITLE
Get a list of sections for a specified boardId not working

### ISSUE THREAD

**Issue by delemore** [seregazhuk/php-pinterest-bot#383]
Hi

Running: `$sections = $bot->boardSections->forBoard($boardId);`

returns this error: _Fatal error: Uncaught seregazhuk\PinterestBot\Exceptions\WrongProvider: Provider seregazhuk\PinterestBot\Api\Providers\Boardsections not found. in /mypath/vendor/seregazhuk/pinterest-bot/src/Api/ProvidersContainer.php:191 Stack trace: #0 /mypath/vendor/seregazhuk/pinterest-bot/src/Api/ProvidersContainer.php(119): seregazhuk\PinterestBot\Api\ProvidersContainer->resolveProviderClass('boardsections') #1 /mypath/vendor/seregazhuk/pinterest-bot/src/Api/ProvidersContainer.php(104): seregazhuk\PinterestBot\Api\ProvidersContainer->addProvider('boardsections') #2 /mypath/vendor/seregazhuk/pinterest-bot/src/Api/ProvidersContainer.php(82): seregazhuk\PinterestBot\Api\ProvidersContainer->getProvider('boardsections') #3 /mypath/test_section.php(30): seregazhuk\PinterestBot\Api\ProvidersContainer->__get('boardSections') #4 {main} thrown in /mypath/vendor/seregazhuk/pinterest-bot/src/Api/ProvidersContainer.php on line 191_

Could you please have a look at this?

**Comment by seregazhuk** [comment]
Hi! I've just checked and it works. Are you using the latest library version?

**Comment by delemore** [comment]
I just updated to the latest Version, but still get this error message.

Here my complete script:

`<?
require('vendor/autoload.php'); 

use seregazhuk\PinterestBot\Factories\PinterestBot;

$bot = PinterestBot::create();

// Login
$bot->auth->login('*****', '*****');


$error = $bot->getLastError();
echo $error;
if($error!='') { echo"$error<hr>"; die();}

echo"Sections<hr>";

$boardid='215258125878669038';

$sections = $bot->boardSections->forBoard($boardid);

echo"<pre>";
print_r($sections);
echo"</pre>";
?>`

**Comment by seregazhuk** [comment]
Just to be sure that you have an updated version. Do you have file `/mypath/vendor/seregazhuk/pinterest-bot/src/Api/Providers/BoardSections.php`?

**Comment by delemore** [comment]
Yes, i do habe this file in my directory.

**Comment by seregazhuk** [comment]
I think that you have missed something. Check your code. I have created an empty project with the latest version and it works.
![pinterest-board-sections](https://user-images.githubusercontent.com/9959761/41172196-c09f8b5e-6b5b-11e8-9441-ee97109df3cb.gif)

**Comment by delemore** [comment]
I even copied manually the complete "src" Folder here from github. I still get error.

**Comment by seregazhuk** [comment]
Have you repeated the steps I've done in the gif above?

**Comment by delemore** [comment]
Yes, I repeated the steps shown in your gif.

Just now I did Change the filename "BoardSections.php" to "Boardsections.php" (no capital S) and I _only_ get this error: bool(false)

**Comment by seregazhuk** [comment]
Oh, I see. It was the filename issue 🤦‍♂️  sorry about that. I'll fix it tomorrow. I think `false` is because in my example I didn't log in and used some random board id.

**Comment by delemore** [comment]
It Looks like? Inbetween I could solve the _bool(false)_ error, I uncommented the Login-part of the script ;-) Right now I am testing some boards. 


Btw: Thank you so much for your support!!

**Comment by seregazhuk** [comment]
Thank you for help with finding the bug :wink: !

**Comment by delemore** [comment]
You're welcome. Glad to help you 👋

**Comment by seregazhuk** [comment]
@delemore I've fixed the issue with filename `BoardSection`. Please update to version `5.7.2` and it will work as expected :wink: 👍
