### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by debasislnsel** [seregazhuk/php-pinterest-bot#393]
Hello tried without proxy and with proxy. but still login is not happening. always return NULL

$bot->getHttpClient()->useProxy('198.245.69.75', '4444','xxxxxxxx:xxxxxxx');

//var_dump($bot->getLastError());

$result = $bot->auth->login("xxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx");

ERROR:

Fatal error: Uncaught seregazhuk\PinterestBot\Exceptions\AuthRequired: Error calling seregazhuk\PinterestBot\Api\Providers\User::isBanned method. You must log in before. in /home/happyhosting/public_html/curesciaticapain.com/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Core/ProviderWrapper.php:66 Stack trace: #0 /home/happyhosting/public_html/curesciaticapain.com/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Core/ProviderWrapper.php(42): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->checkMethodForLoginRequired('isBanned') #1 /home/happyhosting/public_html/curesciaticapain.com/php-pinterest-bot-master/examples/auto_pins.php(35): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->__call('isBanned', Array) #2 {main} thrown in /home/happyhosting/public_html/curesciaticapain.com/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Core/ProviderWrapper.php on line 66

**Comment by seregazhuk** [comment]
Can you login without proxy?

**Comment by seregazhuk** [comment]
Closed due to no feedback
