### ISSUE TITLE
Unable to get Followers for any Account!

### ISSUE THREAD

**Issue by KJ1i** [seregazhuk/php-pinterest-bot#394]
Hi there,

Recently, I am unable to get followers of any account. Previously, I was able to get followers perfectly (without even logging in with this), but now I am unable to.

Can you please fix it?
It will be really appreciated. Thanks!

Here is a small test code I use, now all it 'echoes' is a blank page:-

```
require('vendor/autoload.php');
use seregazhuk\PinterestBot\Factories\PinterestBot;
$bot = PinterestBot::create();
$peopleToFollow = $bot->pinners->followers('xxxxxxxxxxxxx')->toArray();

foreach($peopleToFollow as $user) {
echo $user['username'] . ",";
}
```

**Comment by KJ1i** [comment]
I fixed it by logging into Pinterest first and then getting the Followers.
Thanks for this amazing bot! @seregazhuk

**Comment by seregazhuk** [comment]
Hm, looks like Pinterest has changed their API and now require being logged in 👍
