### ISSUE TITLE
Please add "Leave Board"

### ISSUE THREAD

**Issue by delemore** [seregazhuk/php-pinterest-bot#398]
Hi,

could you please add the functionallity to leave a specific board?

This would be much appreciated.

**Comment by seregazhuk** [comment]
Hi! It's done in a new release `5.8.0`.
Check the docs [here](https://github.com/seregazhuk/php-pinterest-bot/blob/master/docs/boards.md#leave-board).

**Comment by delemore** [comment]
Great!! Thank you so much!!!!

 

Von: Sergey Zhuk <notifications@github.com> 
Gesendet: Samstag, 7. Juli 2018 21:00
An: seregazhuk/php-pinterest-bot <php-pinterest-bot@noreply.github.com>
Cc: delemore <kay.spohr@gate2world.ch>; Author <author@noreply.github.com>
Betreff: Re: [seregazhuk/php-pinterest-bot] Please add "Leave Board" (#398)

 

Hi! It's done in a new release 5.8.0.
Check the docs here <https://github.com/seregazhuk/php-pinterest-bot/blob/master/docs/boards.md#leave-board> .
