### ISSUE TITLE
Get all invated user's my board

### ISSUE THREAD

**Issue by ug-code** [seregazhuk/php-pinterest-bot#403]
hi

I use this method

`$bot->boards->sendInvite($boardId, $userId);`

How can I see who I have already invited to board ?

maybe the code should be like this:

``` 
if($bot->boards->isInvited($boardId, $userId)){
    $bot->boards->sendInvite($boardId, $userId)
}
or 

$bot->boards->getInvited($boardId, $userId)

```

**Comment by seregazhuk** [comment]
Hi! Pinterest returns the following response:
<img width="1297" alt="2018-07-27 21 30 07" src="https://user-images.githubusercontent.com/9959761/43340257-6f28a1ac-91e4-11e8-90c5-1508a604e026.png">

I can add something like 
```php
$invites = $bot->boards->getInvites($boardId);
```

and then the calling code can take what it needs from this response. What do you think about this?

**Comment by ug-code** [comment]
yes, this is what I want.  Thank you :blush:

**Comment by seregazhuk** [comment]
Use [this method](https://github.com/seregazhuk/php-pinterest-bot/blob/master/docs/boards.md#get-invites-for-board): 
```php
$bot->boards->invites()
```.
I think it is what you need.

**Comment by seregazhuk** [comment]
@ug-code oh I see.
Update to version `v5.8.1` and use this code:

```php
foreach($bot->boards->invitesFor($boardId) as $invite) {
    // loop through invites
}
```

I've updated the [docs](https://github.com/seregazhuk/php-pinterest-bot/blob/master/docs/boards.md#get-invites-for-a-board).

Hope it works 😉

**Comment by ug-code** [comment]
it works fine. :+1: 
Thank you @seregazhuk
