### ISSUE TITLE
problem getting boards from account

### ISSUE THREAD

**Issue by hhitch** [seregazhuk/php-pinterest-bot#410]
there is one profile that the bot cannot get the boards from and I noticed it's one that was apparently upgraded to a business account. Is there an issue getting boards from business accounts or any other type of account? All my other accounts will list the boards fine but this one comes up with empty array every time.

I've tried both of these calls:

$boards = $bot->boards->forMe();
$boards = $bot->boards->forUser($me_username);

both are the same - empty array. And I have six boards full of pins on that account running for about six years now

all my other accounts are pulling the boards just fine, it's only this one account that just does not pull the boards from.

By the way, I discovered that I can pull the boards from this account using the official API but not with the bot

any thoughts? thanks in advance :) h.

**Comment by seregazhuk** [comment]
Hi! Can you please provide your username?

**Comment by hhitch** [comment]
is there some way I can send it privately seregazhuk? thanks

**Comment by seregazhuk** [comment]
Yes, send email it to me. Use email in my GitHub profile.

**Comment by lemonade-coding** [comment]
Hello!

I have the same problem as hhitch described. There is _one_ account for which I can't get a boards list but get an empty array and a message: 'Похоже, произошла ошибка'.

**Comment by seregazhuk** [comment]
I need more information to solve the problem. As I've said before I cannot reproduce the bug by self. I need credentials from the account with the following issue. You provide a pull request with a fix.

**Comment by lemonade-coding** [comment]
I've found one solution already. 

Where you have:

    public function forUser($username)
    {
        $options = [
            'username'      => $username
          //  'field_set_key' => 'detailed',
        ];

        $result = $this->get(UrlBuilder::RESOURCE_GET_BOARDS, $options);

        return $result ?: [];
    }

I've commented 'field_set_key' => 'detailed'. 

My version of what caused an issue is that for some accounts a list of 'detailed' boards is too big array for to proceed it. For an account with a problem I have 51 boards. Other accounts with smaller numbers of boards worked fine. 

Another possible solution from my point of view can be something with pagination. So, that I can control a number of boards which I get. First 20 boards, next 20 boards, ..., like it is for pins.

Thanks!

**Comment by hhitch** [comment]
Thanks Lemonade, will check that out.

In my case this is an easily reproducable bug -- I have been able to reproduce this with my own and other users' accounts and also the same fix works.

How to reproduce the issue: use an account that has been "upgraded" to a "business account" on Pinterest. Those accounts can reliable fail to pull boards using $boards = $bot->boards->forMe() or $boards = $bot->boards->forUser($username).

This is a reliable, re-creatable issue. Just use any Pinterest account that is a "business account" 

While the bot does not pull the boards for those accounts, the regular Pinterest API will pull those boards for said accounts. we now see this as a standard issue - users with business account cannot pull boards with bot

**Comment by lemonade-coding** [comment]
hhitch, hello!

In my case bot works fine also for business accounts.

**Comment by hhitch** [comment]
Hi again I just wanted to follow up and say it seems with a more recent release of the library this issue has gone away. Sorry to pester you about it and keep up the great work :+1:

**Comment by lemonade-coding** [comment]
O'k! That's good news. Thanks.
