### ISSUE TITLE
possible get Pinner info by ID instead of username?

### ISSUE THREAD

**Issue by hhitch** [seregazhuk/php-pinterest-bot#411]
Hi there, I have situations where I have just the ID of the pinner and I need to get their username. If I do $bot->pinners->info($userid) it returns error "No url". I checked the source code and I see it only takes the Username. Is there some way to query the pinner info using their ID instead of their username?

thanks much in advance! -H.

**Comment by seregazhuk** [comment]
Hi! @hhitch where did you get this ID? Actually Pinterest API uses only username to fetch this data :( maybe you can find the way to fetch ID and username?

**Comment by hhitch** [comment]
like if we're searching pinners by board and it just has $board['owner']['id'] and no username. How to get the username -- I was thinking $bot->users->profile($board['owner']['id']) but so far I haven't figured it out completely

**Comment by seregazhuk** [comment]
Closed due to no feedback.
