### ISSUE TITLE
Title (Creating new Pin)

### ISSUE THREAD

**Issue by delemore** [seregazhuk/php-pinterest-bot#418]
When I create a new pin on Pinterest, I can specify a title. Unfortunately this does not seem possible in your bot. Can you please add this feature occasionally?

**Comment by seregazhuk** [comment]
I cannot find the title on Pinterest, only a description. Can you provide a screenshot, please?

**Comment by delemore** [comment]
![screenshot](https://user-images.githubusercontent.com/16901947/46903805-a9194c80-ceda-11e8-86c5-a492359a8d96.jpg)

Maybe the title can only be set with a Pinterest business profile?

**Comment by seregazhuk** [comment]
I also have a business account, but unfortunately, I don't have this feature in browser 😞

**Comment by delemore** [comment]
Sorry, I have expressed myself unclear. It's about setting a title for "Rich Pins" in the Business Account:

http://thecontentbug.com/2017/02/07/add-titles-to-your-pins/

**Comment by seregazhuk** [comment]
Sorry, but the bot doesn't support reach pins 😞

**Comment by delemore** [comment]
That's really a pity :weary:

**Comment by seregazhuk** [comment]
I'll try to implement this

**Comment by seregazhuk** [comment]
@delemore Hi! If you are still interested, now you can specify a title for a pin:

```php
```php
$pinInfo = $bot->pins->create(
    'http://exmaple.com/image.jpg',
    $boardId,
    'Pin description',
    'http://site.com',
    'Pin title'
);
```

Or when editing a pin:
```php
$bot->pins->edit($pinId, 'new description', 'new link', $newBoardId, 'new title');
```

The only thing you need to do is to install the `dev` version of the package. I haven't tagged a release yet:

```bash
composer require seregazhuk/pinterest-bot:dev-master 
```
