### ISSUE TITLE
Issue while setting up the program

### ISSUE THREAD

**Issue by nomikk92** [seregazhuk/php-pinterest-bot#419]
composer require seregazhuk/pinterest-bot

--------------------------
 
Problem 1
    - seregazhuk/pinterest-bot v5.8.2 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - seregazhuk/pinterest-bot v5.8.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - seregazhuk/pinterest-bot 5.8.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - Installation request for seregazhuk/pinterest-bot ^5.8 -> satisfiable by seregazhuk/pinterest-bot[5.8.0, v5.8.1, v5.8.2].

  To enable extensions, verify that they are enabled in your .ini files:
    - D:\Program Files\php-7.2.10-nts-Win32-VC15-x64\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

--------------------------

I am noob at coding can someone show me how to fix this?

**Comment by rjkhan** [comment]
install curl on your computer

**Comment by seregazhuk** [comment]
@rjkhan is right 👍  Composer says that you need to install cURL PHP extension.
