### ISSUE TITLE
Accounts suspended when created using the bot

### ISSUE THREAD

**Issue by aabudara** [seregazhuk/php-pinterest-bot#420]
I have created 2 accounts using the bot and they were suspended immediately.   Have you experienced something similar?  Is there any thing I should do to prevent this?

**Comment by aabudara** [comment]
I forgot to mention, I have created manual accounts with the same proxy and they worked ok after that.

**Comment by seregazhuk** [comment]
Hi! Seems like your IP address is black-listed.
