### ISSUE TITLE
Pagination is extremely slow for a profile with a lot of followers

### ISSUE THREAD

**Issue by vladoa** [seregazhuk/php-pinterest-bot#422]
If I take a profile like this:

```
$id = '470555998474494414';
	
$limit = 500;
	
$offset = 2000;

$followers = $bot->pinners->followers($id, $limit)->skip($offset)->get();
```
which has like 59k followers, it takes around 2 minutes to execute

whereas by using $limit = 500 and $offset = 0 it takes around 30 seconds.
So if the user has 59k followers, and I put $offset = 58500; the script takes forever to execute.

Any ideas how to deal with profiles with many followers?

**Comment by seregazhuk** [comment]
Hi. You are right. Unfortunately, under the hood, the bot has to loop through all previous followers. Pinterest doesn't provide explicit API for it. So, the bot behaves exactly like the site.

**Comment by vladoa** [comment]
I thought so. I think I will just write some javascript that will scroll down and grab the usernames.
Still, I really like your project and I appreciate your answer!
