### ISSUE TITLE
Info Required

### ISSUE THREAD

**Issue by paksociety** [seregazhuk/php-pinterest-bot#438]
HI, I want to know how we can get the url to pin we created using this script? this is not an issue and please suggest me a way to ask questions on github.

**Comment by paksociety** [comment]
Also a way to delete created pin if we want to delete them

**Comment by MaurieF** [comment]
I would just run:
$bot->pinners->pins(PinterestUsername, NumberOfPins) ->toArray();
Then use the result to grab the data you need.

e.g. To get the last 20 pins by louisemyers...
$pusername = 'louisemyers';
$RecentPins = $bot->pinners->pins($pusername, 20) ->toArray();

Then a for each to return the info you want to include:
foreach($RecentPins as $pinfo){
	echo  '<div style = "display: inline-block; margin: 5px 0px 5px 15px; padding: 0px 5px 0px 0px; border: 1px solid #cccccc; border-radius: 4px;"><a href = "' .$pinfo[images]['736x'][url]. '" target = "_blank"><img style = "margin: 5px 5px 0px 5px;" src = "'.$pinfo[images]['136x136'][url].'" </a>URL: <a href = "https://pinterest.com/pin/' .$pinfo[id].'"target = "_blank">https://pinterest.com/pin/'.$pinfo[id].'</a><br/>Pin ID: ' .$pinfo[id].'<br/> Time Created: ' .$pinfo[created_at].'</div><br/>';
}
This would produce html output similar to this snapshot:
![marthadisp](https://user-images.githubusercontent.com/25314520/52393977-76800900-2af4-11e9-9d01-caa563b55a0e.png)

**Comment by Iquaridys** [comment]
@MaurieF can u email me you last file for this pinterest bot? i got loots error, especially when logging in.
please, share you last editing files. you can upload it or email me to syauqidirgantara@gmail.com>

thanks before

**Comment by MaurieF** [comment]
Hi @Iquaridys ,
The login issue has been fixed in the latest release....you can find it [HERE](https://github.com/seregazhuk/php-pinterest-bot/releases/tag/v5.9.1)

I have no problems using the login method with that version.
So, make sure you have updated to the newest version f the bot and 
that you are running php 7.

**Comment by MaurieF** [comment]
Not sure what is happening for you..
I have added a small pdf for you to see working code..
its [HERE](https://github.com/MaurieF/test/blob/master/LoginTest.pdf)
