### ISSUE TITLE
Login With Cookies

### ISSUE THREAD

**Issue by henzan02** [seregazhuk/php-pinterest-bot#440]
hello,

can I login with cookies? 

I get some error and I have no idea to fix it on my account. 

`Fatal error: Uncaught seregazhuk\PinterestBot\Exceptions\AuthRequired: Error calling seregazhuk\PinterestBot\Api\Providers\Boards::forMe method. You must log in before. in C:\xampp\htdocs\pin\dashboard\vendor\seregazhuk\pinterest-bot\src\Api\Providers\Core\ProviderWrapper.php:66 Stack trace: #0 C:\xampp\htdocs\pin\dashboard\vendor\seregazhuk\pinterest-bot\src\Api\Providers\Core\ProviderWrapper.php(42): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->checkMethodForLoginRequired('forMe') #1 C:\xampp\htdocs\pin\dashboard\myboard.php(13): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->__call('forMe', Array) #2 {main} thrown in C:\xampp\htdocs\pin\dashboard\vendor\seregazhuk\pinterest-bot\src\Api\Providers\Core\ProviderWrapper.php on line 66`

Could you please give me an explanation. 

Thanks

**Comment by seregazhuk** [comment]
Duplicate with https://github.com/seregazhuk/php-pinterest-bot/issues/442
