### ISSUE TITLE
Login method not working

### ISSUE THREAD

**Issue by derkleinemukk** [seregazhuk/php-pinterest-bot#442]
Same as reported by someone else. 

Login method doesn't seem to work, error message when calling the isBanned method.
Fatal error: Uncaught seregazhuk\PinterestBot\Exceptions\AuthRequired: Error calling seregazhuk\PinterestBot\Api\Providers\User::isBanned method. You must log in before

Tried:
var_dump($bot->getLastError());
output
NULL

Tried the credentials in the browser, working fine there. Account not blocked etc.

**Comment by mimini0147** [comment]
same here, account seem not blocked, still getting traffic but PHP bot didn't work, maybe an new update from Pinterest?

**Comment by asperduti** [comment]
Same problem here. I can log in the browser with the same credentials used in the bot.

**Comment by seregazhuk** [comment]
Yes, looks like Pinterest has changed its API 😞

**Comment by MaurieF** [comment]
Sergey,
Do you think the login issue can be resolved?
Similar to other users, my sign in credentials work in the browser.

**Comment by seregazhuk** [comment]
>Do you think the login issue can be resolved?

Not now. Currently, I don't have free time to fix it 😞

**Comment by derkleinemukk** [comment]
Would be happy to help with resolving it, do you already have an idea at what needs to be changed where? Pinterest docs only talk about oAuth with a registered app, so that's not really helpful. 

The URL you're using to create the user session
https://www.pinterest.co.uk/resource/UserSessionResource/create/
does work in the browser (based on cookies I also get my user info back in the browser, so the endpoint itself is working).

**Comment by tuxado** [comment]
any solution ?

**Comment by Nurichief** [comment]
any solution ? help!

**Comment by seregazhuk** [comment]
>Didn't get much further with my digging, but maybe you did?!

Yes, I did. And they have changed the whole authentication system. It is not a matter of one request. So feel free to provide PR to fix it.

**Comment by MaurieF** [comment]
I am happy to help....., just need a little bit of guidance to get  started...
Is there anywhere I can see the authentication system?

**Comment by mimini0147** [comment]
> > Didn't get much further with my digging, but maybe you did?!
> 
> Yes, I did. And they have changed the whole authentication system. It is not a matter of one request. So feel free to provide PR to fix it.

when I try to use Postman for post request, Pinterest returns always the page "need to activate Javascript".  
But in the Cookie we can find "csrftoken"

**Comment by tuxado** [comment]
> I am happy to help....., just need a little bit of guidance to get started...
> Is there anywhere I can see the authentication system?
> In my use of the bot, I really only require logging in to get pin activity.
> All other parts of the bot, as far as I can see, work very well.

use chrome extension like Web Sniffer to trace login process and find the variables and the way that use pintreset to login

for debugging the request of this package edit ( C:\...\vendor\seregazhuk\pinterest-bot\src\Api\CurlHttpClient.php ) and add before the return line of [function init($url, $postString, $headers)] this lines 

curl_setopt($this->curl, CURLOPT_VERBOSE, true);
$verbose = fopen('c:\\temp.txt', 'a+');
curl_setopt($this->curl, CURLOPT_STDERR, $verbose);

1) for registration of new account it work and the response of bot->register() give auth=1 but i suggest to save the cookies response _pinterest_sess and csrftoken to autologin (to prevent pinterest ban)

2) for the login still not working

**Comment by mimini0147** [comment]
> > I am happy to help....., just need a little bit of guidance to get started...
> > Is there anywhere I can see the authentication system?
> > In my use of the bot, I really only require logging in to get pin activity.
> > All other parts of the bot, as far as I can see, work very well.
> 
> use chrome extension like Web Sniffer to trace login process and find the variables and the way that use pintreset to login
> 
> for debugging the request of this package edit ( C:...\vendor\seregazhuk\pinterest-bot\src\Api\CurlHttpClient.php ) and add before the return line of [function init($url, $postString, $headers)] this lines
> 
> curl_setopt($this->curl, CURLOPT_VERBOSE, true);
> $verbose = fopen('c:\temp.txt', 'a+');
> curl_setopt($this->curl, CURLOPT_STDERR, $verbose);
> 
> for @seregazhuk
> 
> 1. for registration of new account it work and the response of bot->register() give auth=1 but i suggest to save the cookies response _pinterest_sess and csrftoken to autologin (to prevent pinterest ban) at Auth.php
>    ``
>    /**
>    
>    * @param Registration $registrationForm
>    * @return bool|mixed
>      */
>      protected function makeRegisterCall(Registration $registrationForm)
>      {
>      if (!$this->sendEmailVerificationAction()) {
>      return false;
>      }
>      > > >
>      
>      
>      $data = $registrationForm->getData();
>      $this->request->loadCookiesFor($data['email']);
>      <<< line to add
>      if (!$this->post(UrlBuilder::RESOURCE_CREATE_REGISTER, $registrationForm->toArray())) {
>      return false;
>      }
>      if (!$this->sendRegistrationActions()) {
>      return false;
>      }
>      return $this->completeRegistration();
>      }
> 
> ``
> 
> 1. i change also the URL_BASE and HOST at  \vendor\seregazhuk\pinterest-bot\src\Helpers\UrlBuilder.php i notice that pinterest not share correctly the cookies between subdomain
>    const URL_BASE = 'https://www.pinterest.com/';
>    const HOST = 'www.pinterest.com';
> 2. for the login still not working  and an alternative and tomporary solution is using bot->register() to login like edited in (1)

this didnt work for me... call $bot->auth->register() function with existing account will return false

**Comment by MaurieF** [comment]
Thanks for the guidance @tuxado ...
I cannot get $bot->auth->register() to work for an existing account.
I dont know if its relevant, but when logging in through Pinterest it sends requests to

**Comment by tuxado** [comment]
Hi, Now it work only when you register new account. i create a fork to explain you how you can edit the vendor at https://github.com/tuxado/php-pinterest-bot 

foreach action ContextLogResource, ActiveUserResource, EmailExistsResource and so ...... create a Trait file on php-pinterest-bot/src/Api/Traits/ like for example the EmailExistsResource that i created and before the login process you can call each request action from the Trait.

Note some actions aren't important for the login process. Also pinterest check if the request come from a real browser and from the same **Orgin** of The **Host** it why you get **404** it is why i use www.pinterest.com and not uk.pinterest.com but note also that the www.pinterest.com sometimes it can return some errors

**Comment by tuxado** [comment]
I look like the login rework using this update https://github.com/tuxado/php-pinterest-bot
.
> [INFO] Account : patrick.batz.*@gmail.com
> [INFO] Account login success

waiting confirmation

**Comment by anasnawaz** [comment]
Error calling seregazhuk\PinterestBot\Api\Providers\User::isBanned method. You must log in before


login fail and return this error plz anyone can help me thanks advance  @seregazhuk

**Comment by anasnawaz** [comment]
also your examples is not working @seregazhuk

**Comment by tuxado** [comment]
@anasnawaz use this package https://github.com/tuxado/php-pinterest-bot download it manually from the browser unzip it and copy and replace the main package on vendor/seregazhuk/php-pinterest 

'
$bot = PinterestBot::create();
$bot->auth->login("example@example.com", "password");
if($bot->auth->isLoggedIn())
{
	if (!$bot->user->isBanned()) 
	{
		echo ' > [INFO] Account login success';
	}
}

**Comment by anasnawaz** [comment]
bundle of thanks  for help

**Comment by MaurieF** [comment]
Thanks @tuxado 
The new fork does achieve login and I'm now able to run $bot->pins->activity($pinid,25) ->toArray();
which is login dependent.

**Comment by seregazhuk** [comment]
Thank you @tuxado 
Actually, the issue was only with the domain. You should use `www.pinterest.com` instead of country-specific `uk.pintrerest.com` 🤦‍♂️ 

Everybody, I have published a new release `v5.9.1` with fixes. Please, update you versions.

**Comment by MaurieF** [comment]
Thanks @seregazhuk

**Comment by ihturkmen** [comment]
@seregazhuk Thanks 👍

**Comment by buildingnicko** [comment]
when my script loads in the browser there is an error "Sorry! We've had to block actions (logins) from your area because of suspicious activity. Please try again later." How can I handle it?
![pinterest](https://user-images.githubusercontent.com/49529886/56023834-fb77e080-5d38-11e9-954d-e527ca370d9e.png)

**Comment by sonerss** [comment]
> Thank you @tuxado
> Actually, the issue was only with the domain. You should use `www.pinterest.com` instead of country-specific `uk.pintrerest.com` 🤦‍♂️
> 
> Everybody, I have published a new release `v5.9.1` with fixes. Please, update you versions.

Hello,

How can I update php-pinterest-bot v5.9.1?

when I run "composer require seregazhuk/pinterest-bot" in cmd, it loads "Installing 

seregazhuk/pinterest-bot (5.7.3): Loading from cache"

BR

**Comment by tuxado** [comment]
> > Thank you @tuxado
> > Actually, the issue was only with the domain. You should use `www.pinterest.com` instead of country-specific `uk.pintrerest.com` man_facepalming
> > Everybody, I have published a new release `v5.9.1` with fixes. Please, update you versions.
> 
> Hello,
> 
> How can I update php-pinterest-bot v5.9.1?
> 
> when I run "composer require seregazhuk/pinterest-bot" in cmd, it loads "Installing
> 
> seregazhuk/pinterest-bot (5.7.3): Loading from cache"
> 
> BR

edit your composer.json 
"seregazhuk/pinterest-bot": "^5.9.1",
and open CMD and type : composer update

or use require

composer require vendor/package:version

composer require seregazhuk/pinterest-bot:5.9.1

or

composer require vendor/package "version"

composer require seregazhuk/pinterest-bot "^5.9.1"

**Comment by gonjumixproject** [comment]
started to observe this issue now with v5.9.1 :(

**Comment by mtnyvz16** [comment]
I'm having the same problems again :(
 Please help immediately.

**Comment by mtnyvz16** [comment]
I'm having the same problems again :(
 Please help @seregazhuk  @tuxado

**Comment by policemal** [comment]
v5.9.1 doesn't work on me either. I keep getting the following error. friends please help me. @seregazhuk @tuxado

... Error calling seregazhuk\PinterestBot\Api\Providers\User::isBanned method. You must log in before. in ...

**Comment by garsamba** [comment]
> > > Thank you @tuxado
> > > Actually, the issue was only with the domain. You should use `www.pinterest.com` instead of country-specific `uk.pintrerest.com` man_facepalming
> > > Everybody, I have published a new release `v5.9.1` with fixes. Please, update you versions.
> > 
> > 
> > Hello,
> > How can I update php-pinterest-bot v5.9.1?
> > when I run "composer require seregazhuk/pinterest-bot" in cmd, it loads "Installing
> > seregazhuk/pinterest-bot (5.7.3): Loading from cache"
> > BR
> 
> edit your composer.json
> "seregazhuk/pinterest-bot": "^5.9.1",
> and open CMD and type : composer update
> 
> or use require
> 
> composer require vendor/package:version
> 
> composer require seregazhuk/pinterest-bot:5.9.1
> 
> or
> 
> composer require vendor/package "version"
> 
> composer require seregazhuk/pinterest-bot "^5.9.1"

Iz there any update?
