### ISSUE TITLE
Tutorial run

### ISSUE THREAD

**Issue by Iquaridys** [seregazhuk/php-pinterest-bot#444]
Can someone teach me to run it?

install composer | done
require seregazhuk/php-pinterest-bot | done

but how to run it?
when i try run, get to many error,
the error show like no directory  and cant login 

can someone teamviewer my pc?
thanks

**Comment by ihturkmen** [comment]
Pinterest has changed its API #442

**Comment by MaurieF** [comment]
You should still be able to run methods that don't require a login.
If you create a file like below upload to your server and run it..
<?php
require('vendor/autoload.php');  //Change to correct directory for your installation
use seregazhuk\PinterestBot\Factories\PinterestBot;  //Change to correct directory for your installation
$bot = PinterestBot::create();


     //recommended keywords for christmas tree
$keywords = $bot->keywords->recommendedFor('christmas tree');
	echo '<pre/>';
    print_r($keywords);

   
$pdata =$bot->pinners->info('marthastewart');	
	echo '<pre>';
	print_r($pdata);

 //last 20 pins by Martha Stewart	
$pusername = 'marthastewart';
$RecentPins = $bot->pinners->pins($pusername, 20) ->toArray();
foreach($RecentPins as $pinfo){
	echo  '<div style = "display: inline-block; margin: 5px 0px 5px 15px; padding: 0px 5px 0px 0px; border: 1px solid #cccccc; border-radius: 4px;"><a href = "' .$pinfo[images]['736x'][url]. '" target = "_blank"><img style = "margin: 5px 5px 0px 5px;" src = "'.$pinfo[images]['136x136'][url].'" </a>URL: <a href = "https://pinterest.com/pin/' .$pinfo[id].'"target = "_blank">https://pinterest.com/pin/'.$pinfo[id].'</a><br/>Pin ID: ' .$pinfo[id].'<br/> Time Created: ' .$pinfo[created_at].'</div><br/>';
}

**Comment by Iquaridys** [comment]
@MaurieF Thanks but how to add for login? i want to don pin image to my pinterest account

**Comment by MaurieF** [comment]
As @ihturkmen commented above, the login method is currently not working...there is a discussion about it on issue #442 .
You should read through that...

**Comment by seregazhuk** [comment]
Hi @Iquaridys 
Log in issue has been fixed. To create pin use [this doc](https://github.com/seregazhuk/php-pinterest-bot/blob/master/docs/pins.md#create-a-pin).
