### ISSUE TITLE
board->forMe() Not Working

### ISSUE THREAD

**Issue by henzan02** [seregazhuk/php-pinterest-bot#446]
Hello, 
I'm very pleased there's an update. 

I have used the latest version but its not working for getting my own board. 

here's my code. 

```
require('vendor/autoload.php'); 

use seregazhuk\PinterestBot\Factories\PinterestBot;
$bot = PinterestBot::create();
$bot->auth->login('usename@gmail.com', 'pass');

$boards = $bot->boards->forMe();

print_r($boards);
```

Result : 
```
Array
(
)
```
is there any mistakes in my code?

Thanks

**Comment by seregazhuk** [comment]
Hi @henzan02 
I cannot reproduce. Please make sure that you have the latest version of the library and try to force log in by providing `false` as the third argument:

```php
$bot->auth->login('usename@gmail.com', 'pass', false);
```

**Comment by henzan02** [comment]
> Hi @henzan02
> I cannot reproduce. Please make sure that you have the latest version of the library and try to force log in by providing `false` as the third argument:
> 
> ```
> $bot->auth->login('usename@gmail.com', 'pass', false);
> ```

It works mate, Thank you very very very much..
