### ISSUE TITLE
spam alert

### ISSUE THREAD

**Issue by netalan** [seregazhuk/php-pinterest-bot#449]
after 100 pin. Why ?
Sorry! You've hit a block (Pins) we have in place to combat spam. Please try again later!

**Comment by seregazhuk** [comment]
Check this https://github.com/seregazhuk/php-pinterest-bot#how-to-avoid-ban

**Comment by Storade** [comment]
I don't add hundreds of pins per minute. Adds a pin every 20 minutes. same alert after 6-7 pin

**Comment by netalan** [comment]
> Bu [https://github.com/seregazhuk/php-pinterest-bot#how-to-avoid-ban adresine bakın.](https://github.com/seregazhuk/php-pinterest-bot#how-to-avoid-ban)

I don't add hundreds of pins per minute. Adds a pin every 20 minutes. same alert after 6-7 pin

**Comment by seregazhuk** [comment]
Maybe your IP got banned. Ask directly to Pintresert support what is the reason of your ban 🤔
