### ISSUE TITLE
Can i combine this with javascript?

### ISSUE THREAD

**Issue by Iquaridys** [seregazhuk/php-pinterest-bot#450]
i want run repeat. For javascript i can use setInterval().
for PHP i only know use cron jobs.

can i combine this file with javascript method?

**Comment by delemore** [comment]
In PHP, you could use `sleep ()`

But I prefer cron jobs ...

**Comment by seregazhuk** [comment]
@Iquaridys please, ask library-related questions here, not infrastructure ones.
