### ISSUE TITLE
How to limit 

### ISSUE THREAD

**Issue by Iquaridys** [seregazhuk/php-pinterest-bot#452]
i want follow user, but i dont want follow all user in 1 day
$bot->pinners->followers('babyboy')->toArray();
ex :  babyboy have 2212 follower in array.

i just want take 80 follower, how i can do that?
is there a feature to limit it?
and if I do it again, the user I have followed will cause an error or even unffolow?

**Comment by tuxado** [comment]
try

$bot->pinners->followers('babyboy', 80)->toArray();
