### ISSUE TITLE
$bot->auth->login('email', 'password'); returns false

### ISSUE THREAD

**Issue by Kekson** [seregazhuk/php-pinterest-bot#453]
Hello, this method is returning false, Laravel 5.8 PHP 7.2 with curl enabled
any ideas what may be wrong ?

**Comment by tuxado** [comment]
if your code are correct try clear laravel,cache and system cache (linux : /tmp , windows C:\Users\(Username)\AppData\Local\Temp) if the error persist post more code

**Comment by Kekson** [comment]
`<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use seregazhuk\PinterestBot\Factories\PinterestBot;
class IndexController extends Controller
{
    public function index()
    {
        $bot = PinterestBot::create();
        // Login
        dd($bot);
        $check = $bot->auth->login('kekela777@gmail.com', 'kekela1993');
            dd($check); die;
}`

**Comment by Kekson** [comment]
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use seregazhuk\PinterestBot\Factories\PinterestBot;
class IndexController extends Controller
{
    public function index()
    {
        $bot = PinterestBot::create();
        // Login
        $check = $bot->auth->login('my_email', 'my_password');
            dd($check); die;
}
}

**Comment by Kekson** [comment]
It's a great tool, good job!
