### ISSUE TITLE
Dont save cookies , use proxy

### ISSUE THREAD

**Issue by coderiki** [seregazhuk/php-pinterest-bot#454]
$this->bot->getHttpClient()->useProxy($proxy['host'], $proxy['port'], $proxy['auth']);
if (!$this->bot->auth->login($request['email'], $request['password'])) {
       $this->errorMessage = $this->bot->getLastError();
}

I'm using a proxy like the one above, but I'm logged in to the file I'm specifying cookies are not saved. More precisely the cookkies file is being created but is empty. When I am not using a proxy, it is saving cookies.

**Comment by TheYkk** [comment]
any update?

**Comment by seregazhuk** [comment]
Maybe there is something wrong with proxy? I have no details to reproduce the issue. Feel free to reopen if you provide any steps to reproduce the bug.
