### ISSUE TITLE
Pagination can't get all of followers

### ISSUE THREAD

**Issue by masokky** [seregazhuk/php-pinterest-bot#455]
I've made bot to automatic follow other's follower, but the pagination can't iterate to get all of followers. The bot stopped at first twelve followers, while my target has 7K followers.
This is my code:
```php
$getUsers = $bot->pinners->followers($target);
foreach($getUsers as $user){
	if(!$user["explicitly_followed_by_me"]){
		$follow = ($bot ->pinners->follow($user["id"])) ? "Sukses" : "Gagal";
		echo " [>] ".$user["username"]." -> Follow ".$follow."\n\n";
		echo " [>] Delay for ".$delay." Seconds\n\n";
		sleep($delay);
	}
}
```
How can i fix it?

**Comment by oktayla** [comment]
for( $i = 0; $i < ceil(7000/50); $i++ ) {
$getUsers = $bot->pinners->followers($target)->skip($i*50);
// ...rest
}

*Simply

**Comment by masokky** [comment]
thanks, it's work fine for me
