### ISSUE TITLE
How do I do pagination on search suggestion?

### ISSUE THREAD

**Issue by gyurisc** [seregazhuk/php-pinterest-bot#457]
I was wondering if I can do pagination on search suggestions? I am trying like this but getting an error message when calling it. Is it possible at all on this method? 

`
$suggestions = $bot->suggestions->searchFor($argv[1]) -> skip(20);`
```

Error: Call to a member function skip() on array in C:\dev\github\php-pinterest-bot\examples\suggestions.php
on line 13
```

**Comment by seregazhuk** [comment]
It is not implemented. You get only the first 20 or something results. Feel free to provide a pull request with this implementation 👍

**Comment by gyurisc** [comment]
@seregazhuk I would love to do that. Can you please point me a direction to a working paging code that I can follow, please? I am very new to PHP with lot of background in C#, so this can be a great learning experience for me. :)
