### ISSUE TITLE
Stop working today

### ISSUE THREAD

**Issue by murattikil** [seregazhuk/php-pinterest-bot#460]
Working code started to give this error today.

Parse error: syntax error, unexpected '?' in xxxxxxxxxx/vendor/seregazhuk/pinterest-bot/src/Api/Providers/User.php on line 180

**Comment by tuxado** [comment]
be sur to use php >= 7

**Comment by murattikil** [comment]
I see on cpanel that my site work on php7 but it work on 5.4. I still don't know why. 
I fix it after I contact with hosting company. 

Thank you very much for your advise tuxado.
