### ISSUE TITLE
Repin not found board

### ISSUE THREAD

**Issue by coderiki** [seregazhuk/php-pinterest-bot#461]
Login and get board list.
And get pins;

$trendingTopics = $this->bot->topics->explore();
$firstTopicId = $trendingTopics[0]['id'];
$pins = $this->bot->pins->explore($firstTopicId)->toArray();

And first pin , repin ;

$this->bot->pins->repin($pinId, $boardId, $comment);
$this->checkError();

but return error. => Board not found

**Comment by coderiki** [comment]
I resolve problem. I define boardId int type but it want to string value. Change type to string and resolved.

**Comment by e3restu** [comment]
So how to get boardID? Is it same with boardname? Or something like pin id?

**Comment by yusufonur** [comment]
> So how to get boardID? Is it same with boardname? Or something like pin id?

Example;
$info = $bot->boards->info($username, $board);

Or Example;
$boards = $bot->boards->forUser('my_username');
$boardId = $boards[0]['id']; // get first board id
