### ISSUE TITLE
Block actions (logins)

### ISSUE THREAD

**Issue by pauznet** [seregazhuk/php-pinterest-bot#463]
Hello,
When my script loads in the browser there is an error 
"Sorry! We've had to block actions (logins) from your area because of suspicious activity. Please try again later." How can I handle it?
Thanks you.

**Comment by pauznet** [comment]
Now i have this error:
Sorry! You've hit a block (logins) we have in place to combat spam. Please try again later!

**Comment by pauznet** [comment]
I make a pin every 30 minutes.

**Comment by tuxado** [comment]
there is no solution pinrest not like spammers any more you can try 1 ip for 1 confirmed account with this IP and pin 1 pin per hours lol you should have many ip for many accounts and many money to pay for proxies and all this boy shit

**Comment by seregazhuk** [comment]
Close due to not a library issue
