### ISSUE TITLE
Login error after running for few hours

### ISSUE THREAD

**Issue by carolhng** [seregazhuk/php-pinterest-bot#466]
I am running the bot from my PC using xampp. I create one pin every 15 mins using windows batch file after I on the laptop. For every run, I login first, then pin, then logout.
Cookie file at C:\Users\TANCHI~1\AppData\Local\Temp has content on _auth, _pinterest_sess, _routing_id, csrftoken and _b.

Everytimes, the script running well for 3 to 4 hours, then I got this error and no able to pin anymore.

Fatal error: Uncaught seregazhuk\PinterestBot\Exceptions\AuthRequired: Error calling seregazhuk\PinterestBot\Api\Providers\Pins::create method. You must log in before. in C:\xampp3\htdocs\pinterest\vendor\seregazhuk\pinterest-bot\src\Api\Providers\Core\ProviderWrapper.php:66
Stack trace:
#0 C:\xampp3\htdocs\pinterest\vendor\seregazhuk\pinterest-bot\src\Api\Providers\Core\ProviderWrapper.php(42): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->checkMethodForLoginRequired('create')
#1 C:\xampp3\htdocs\pinterest\php8legs\pinterest.php(265): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->__call('create', Array)
#2 {main}
  thrown in C:\xampp3\htdocs\pinterest\vendor\seregazhuk\pinterest-bot\src\Api\Providers\Core\ProviderWrapper.php on line 66

Cookie file at C:\Users\TANCHI~1\AppData\Local\Temp still there but no content inside. 
I have to off the laptop and rerun the bot on the next day.

I believe the error triggered around here:
	$bot = PinterestBot::create();
	$bot->auth->login('myusername', 'mypassword');

What can be the problem?
BTW, I am using PHP7 and laster V5.9.1 bot. Thx.

**Comment by JoshCourt** [comment]
Hi. I'm getting the same issue also.

**Comment by tuxado** [comment]
probably pinterest block your account don't logout every pin and login for one time and do your pin jobs if the pin job fails force logout and login again

**Comment by seregazhuk** [comment]
@tuxado is right. Probably, Pinterest has blocked you.
