### ISSUE TITLE
Profile update, avatar change not work

### ISSUE THREAD

**Issue by BurakBoz** [seregazhuk/php-pinterest-bot#468]
I tried change avatar with your example documentation it returns true but nothing changes.
I tried update some profile data and it didn't work either.

```
$profileForm = (new Profile())
                    ->setFirstName('Some')
                    ->setLastName('Body')
                    ->setAbout('about me')
                    ->setCountry('UK');
$profile = $bot->user->profile($profileForm);
```

**Comment by tuxado** [comment]
`
								$profileForm = (new Profile())
									->setLastName($faker->lastName)
									->setFirstName($faker->firstName)
									->setUserName($faker->userName)
									->setAbout('about')
									->setLocation(config('pinterest.account.location'))
									->setLocale('locale')
									->setCountry('country')
									->setImage('path/to/your/image.jpg');
								$bot->user->profile($profileForm);

`

**Comment by BurakBoz** [comment]
Im sorry this was my fault @tuxado thanks for response
