### ISSUE TITLE
business account issue

### ISSUE THREAD

**Issue by vminsin** [seregazhuk/php-pinterest-bot#471]
Hello,

I'm trying to open a business account, but always opening a personal account.
Code I use:

First:
$bot->auth->registerBusiness('youremail@gmail.com', 'password', 'BusinessName');

Later:
$bot->auth->registerBusiness('youremail@gmail.com', 'password', 'BusinessName', 'http://yoursite.com');

And Later:
use seregazhuk\PinterestBot\Api\Forms\Registration;

$registration = new Registration('youremail@gmail.com', 'password', 'name');
$registration
    ->setAge(30)
    ->setCountry('DE')
    ->setMaleGender()
    ->setSite('http://yoursite.com');

$bot->auth->registerBusiness($registration);

I tried all of them.

**Comment by oubihis** [comment]
Open personal account & convert to business account,

$bot->auth->convertToBusiness('businessName');
$bot->auth->convertToBusiness('businessName', 'http://yoursite.com');

For more Information **[Business account](https://github.com/seregazhuk/php-pinterest-bot/blob/master/docs/account.md#convert-to-business-account)**
