### ISSUE TITLE
example just returns empty array

### ISSUE THREAD

**Issue by marcesh** [seregazhuk/php-pinterest-bot#474]
```
require('vendor/autoload.php');
use seregazhuk\PinterestBot\Factories\PinterestBot;
$bot = PinterestBot::create();
$pins = $bot->pins->search('cats')->take(100)->toArray();
print_r ($pins);
```

trying this simple example just returns an empty array. what am i doing wrong?

**Comment by uzan000571** [comment]
Hi,

change you command to 

$bot->pins->search($query)->take($nbr)->get()

**Comment by MaurieF** [comment]
marcesh,
That should work...your command works for me. I suspect its a PHP version problem.
