### ISSUE TITLE
How remove sessions history?

### ISSUE THREAD

**Issue by Iquaridys** [seregazhuk/php-pinterest-bot#482]
i know how to get list of sessions with,
$bot->user->sessionsHistory();
but,
how i can remove / revoke the old sessions?

**Comment by seregazhuk** [comment]
There is no such functionality.

**Comment by Iquaridys** [comment]
how i can add it this " https://www.pinterest.com/resource/UserSessionStoreResource/delete/" for evoke sessions? 

a little dizzy to see the flow of your code, because I'm not so good at programming
