### ISSUE TITLE
No repin anymore??

### ISSUE THREAD

**Issue by screamolic** [seregazhuk/php-pinterest-bot#483]
How to repin now?

**Comment by seregazhuk** [comment]
I will close the issue without any details. No context, no code, just a question 🤷‍♂

**Comment by screamolic** [comment]
sorry, my bad english. im wondering , how to repinning . im confused..

**Comment by seregazhuk** [comment]
Sorry, the docs were broken. Here is an example - https://github.com/seregazhuk/php-pinterest-bot/blob/master/docs/pins.md#repin
