### ISSUE TITLE
is it possible to add multiple keywords ?

### ISSUE THREAD

**Issue by gonjumixproject** [seregazhuk/php-pinterest-bot#516]
I would like to ask whether it is possible to add multiple keywords into the pinterest post or not.

Thank you very much..

**Comment by fdciabdul** [comment]
yes , keyword is a description of the post 

so you can add any tag on that

**Comment by gonjumixproject** [comment]
Thank you..

I am using following default code for the keyword selection, but it makes a random keyword selection. 

Is it possible to add all keywords and additionally a description ? 

$keywords =['keyword1', 'keyword2','keyword3','keyword4'];


foreach ( $images as $image) {
        $image = $images[$i];
        $keyword = $keywords[array_rand($keywords)];
        $bot->pins->create($image, $boardId, $keyword, $blogUrl);
        unlink($image);
        $i=$i+1;
        echo "Done";
        sleep(30);
}

**Comment by fdciabdul** [comment]
```php
foreach ( $images as $image) {
$image = $images[$i];
$bot->pins->create($image, $boardId, "THIS IS YOUR KEYWORD", $blogUrl);
unlink($image);
$i=$i+1;
echo "Done";
sleep(30);
}
``

**Comment by gonjumixproject** [comment]
thank you !
