### ISSUE TITLE
Observing the PhP Fatal Error again with the v5.9.1

### ISSUE THREAD

**Issue by gonjumixproject** [seregazhuk/php-pinterest-bot#519]
Hi all, 

I started to observe following error with the v5.9.1, same issue solved with 5.9.1.

Anyone else ?

PHP Fatal error:  Uncaught seregazhuk\PinterestBot\Exceptions\AuthRequired: Error calling seregazhuk\PinterestBot\Api\Providers\User::isBanned method. You must log in before. in /home/composer/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Core/ProviderWrapper.php:66
Stack trace:
#0 /home/composer/vendor/seregazhuk/pinterest-bot/src/Api/Providers/Core/ProviderWrapper.php(42): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->checkMethodForLoginRequired('isBanned')
#1 /home/composer/vendor/auto_pins_values.php(22): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->__call('isBanned', Array)
#2 {main}

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fdciabdul** [comment]
check your account again

**Comment by oleg2k18** [comment]
Im have this error too, but only on fresh registererd accounts. On old accounts all work fine.

**Comment by gonjumixproject** [comment]
> check your account again

Not really sure what you mean by check your account, this waas perfectly working earlier. My account is not banned as well..

**Comment by gonjumixproject** [comment]
It does not gives an error to "getLastError()" but it dumps "amihere", so obviously does not like my userlogin or pass, but I can login correctly with them to the site.. Php.error files are also empty

$result = $bot->auth->login('gonjumixproject@gmail.com', 'xxx');

if(!$result) {
     $error = $bot->getLastError();
	echo $error;
	echo "amihere\n";	die();
}

**Comment by fdciabdul** [comment]
> It does not gives an error to "getLastError()" but it dumps "amihere", so obviously does not like my userlogin or pass, but I can login correctly with them to the site.. Php.error files are also empty
> 
> $result = $bot->auth->login('[gonjumixproject@gmail.com](mailto:gonjumixproject@gmail.com)', 'xxx');
> 
> if(!$result) {
> $error = $bot->getLastError();
> echo $error;
> echo "amihere\n"; die();
> }

i mean check your email and password again , that's like you put wrong email or password

the login function is still works
```php
require('vendor/autoload.php'); 

use seregazhuk\PinterestBot\Factories\PinterestBot;


$bot = PinterestBot::create();
$bot->auth->login('email', 'pass');
$boards  = $bot->boards->forUser('abdulmuttaqin456');

print_r($boards);
```

![Screenshot_2020_1005_223448](https://user-images.githubusercontent.com/31664438/95100284-276ff880-075b-11eb-94a0-533a442a3622.png)

**Comment by gonjumixproject** [comment]
It gives the same output for me as well for "print_r($boards);" did you tried autopinning ?

**Comment by fdciabdul** [comment]
> It gives the same output for me as well for "print_r($boards);" did you tried autopinning ?

it's works as well don't you ?
![Screenshot_2020_1005_233229](https://user-images.githubusercontent.com/31664438/95106914-6144fd00-0763-11eb-9521-79bc36abb8c2.png)

did you try to check account on pinterest web ?
```php
$pin = $bot->pins->create('https://avatars0.githubusercontent.com/u/31664438?s=460&u=251f36d7ab0fb4a74b162be7b18f6cdca8a74f8c&v=4', $boards[0]['id'], 'Pin description');

print_r($pin);
```

see https://pin.it/70U2s2x

**Comment by gonjumixproject** [comment]
same issue for me, and for sure I tried it on pinterest web. Will double check at my linux server but it is not working in the Windows with following error;

  thrown in C:\Program Files (x86)\PHP\v7.0\vendor\auto_pins.php on line 12
[05-Oct-2020 11:41:17 America/Los_Angeles] PHP Fatal error:  Uncaught seregazhuk\PinterestBot\Exceptions\AuthRequired: Error calling seregazhuk\PinterestBot\Api\Providers\Pins::create method. You must log in before. in C:\Program Files (x86)\PHP\v7.0\vendor\seregazhuk\pinterest-bot\src\Api\Providers\Core\ProviderWrapper.php:66
Stack trace:
#0 C:\Program Files (x86)\PHP\v7.0\vendor\seregazhuk\pinterest-bot\src\Api\Providers\Core\ProviderWrapper.php(42): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->checkMethodForLoginRequired('create')
#1 C:\Program Files (x86)\PHP\v7.0\vendor\auto_pins.php(17): seregazhuk\PinterestBot\Api\Providers\Core\ProviderWrapper->__call('create', Array)
#2 {main}
  thrown in C:\Program Files (x86)\PHP\v7.0\vendor\seregazhuk\pinterest-bot\src\Api\Providers\Core\ProviderWrapper.php on line 66

**Comment by gonjumixproject** [comment]
I get my old code, and now its working, thanks
