### ISSUE TITLE
Get board followers not work

### ISSUE THREAD

**Issue by huuvu1109** [seregazhuk/php-pinterest-bot#65]
Hi,

Thank you for your bot. I have tested it and it's really good. But one problem is that the feature to get user following not work. Can you please check. Thanks.

foreach($bot->pinners->following('username') as $followingBatch)
{
    // ...
}

**Comment by seregazhuk** [comment]
Hi, I have checked the  latest version and it works fine. For example this:

```
foreach($bot->pinners->followers('phillekille') as $followes)
{
    print_r($followes);
    die();
}
```

**Comment by huuvu1109** [comment]
Oh no. Just test it again and it works perfectly. I tested it about 3 days ago and it seems that the iterators not work. It only return a batch of followers and stop right after. Thanks very much for your quick response.

**Comment by seregazhuk** [comment]
@huuvu1109 maybe it was something in pinterest itself and it returned empty results, because I haven't done any changes in code these days.
