### ISSUE TITLE
request adding link on each pin

### ISSUE THREAD

**Issue by bowodesign** [seregazhuk/php-pinterest-bot#76]
sorry maybe this is not issue but request, is there any possible to add link to every pinner, i mean right now when i do a pin

`$bot->pins->create('http://exmaple.com/image.jpg', $boards[0]['id'], 'pin description');`

when i try to open the board, and click the image, it goes directly to http://exmaple.com/image.jpg is there any option to add specific link rather than link to the image url, maybe like

`$bot->pins->create('http://exmaple.com/image.jpg','http://google.com', $boards[0]['id'], 'pin description');`

so when i click the image it goes to google.com

**Comment by seregazhuk** [comment]
No, it has not been implemented yet. I'm working on it. I'll release a new version with this today.

**Comment by seregazhuk** [comment]
@bowodesign done. Get the latest version of library (2.5.0). When creating a pin pass your link as the fourth argument:

```php
$pinId = $bot->pins->create('http://exmaple.com/image.jpg', $boards[0]['id'], 'pin description', 'http://site.com');
```

**Comment by bowodesign** [comment]
you know what??
your the best !! thank you :)

**Comment by seregazhuk** [comment]
:+1:
