### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by rl421403** [seregazhuk/php-pinterest-bot#9]
I fresh installed a server and install Apache, PHP 5.6 on Centos 7.1
I uploaded all file one server in `pin` folder and created a `new.php` with sample code.

```php
<?php
use seregazhuk\PinterestBot\PinterestBot;


$bot = new PinterestBot('mypinterestlogin', 'mypinterestpassword');
$bot->login();

$boards = $bot->boards->my();

echo $boards;
```

Added my details in above code and and accessed `new.php` file on browser.

    http://x.x.x.x/pin/new.php

> PHP Fatal error:  Class 'seregazhuk\\PinterestBot\\PinterestBot' not found in /var/www/html/pin/new.php on line 5, referer: http://x.x.x.x/pin/new.php

What's the problem???

**Comment by seregazhuk** [comment]
The problem is that you didn't include library files in your script.

**Comment by rl421403** [comment]
Which file do I need to include.
This is also not working.

```php
<?php

include ( 'src/PinterestBot.php' );

use seregazhuk\PinterestBot\PinterestBot;


$bot = new PinterestBot('mypinterestlogin', 'mypinterestpassword');
$bot->login();

$boards = $bot->boards->my();

echo $boards;
```

**Comment by seregazhuk** [comment]
Install library via composer and then use composer autoload file.
