### ISSUE TITLE
Ask for supporting new feature

### ISSUE THREAD

**Issue by thuthao123** [seregazhuk/php-pinterest-bot#97]
Dear author,
I must say that your tool is awesome. Could I ask for one more feature about User Settings. Can you plz support to upload the profile picture for account automatically, Maybe it should look like: $bot->user->profile([profile_image'=>'my-selfie.jpg']);

**Comment by seregazhuk** [comment]
Hi, @thuthao123 ! Thank you for your request. It will be done today.

**Comment by seregazhuk** [comment]
@thuthao123 done! Try this:
```php
$bot->user->profile([
	'profile_image' => $path_to_file
]);
```

**Comment by thuthao123** [comment]
@seregazhuk : I tested it. It works fine now. Thanks very much!
